const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const root=process.cwd();
const indexPath=path.join(root,'index.html');
const core=['content.js'];
const runtime=`(()=>{'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const subjectData=[
{name:'Türkçe',icon:'📖',tone:'blue',group:'gy',pct:86,topics:['Sözcükte Anlam','Cümlede Anlam','Paragraf','Dil Bilgisi','Yazım Kuralları','Noktalama']},
{name:'Matematik',icon:'▦',tone:'violet',group:'gy',pct:61,topics:['Temel Kavramlar','Sayılar','Bölme-Bölünebilme','Problemler','Oran-Orantı','Kümeler','Fonksiyon','Permütasyon']},
{name:'Tarih',icon:'🏛',tone:'red',group:'gk',pct:78,topics:['İlk Türk Devletleri','Osmanlı Kuruluş','Osmanlı Kültür','Kurtuluş Savaşı','Atatürk İlkeleri','Cumhuriyet Dönemi']},
{name:'Coğrafya',icon:'🌐',tone:'blue',group:'gk',pct:70,topics:['Türkiye Fiziki Coğrafyası','İklim','Nüfus','Bölgeler','Harita Bilgisi']},
{name:'Vatandaşlık',icon:'⚖',tone:'orange',group:'gk',pct:84,topics:['Hukukun Temelleri','Anayasa','Yasama','Yürütme','Yargı','İdare Hukuku']},
{name:'Güncel Bilgiler',icon:'▤',tone:'violet',group:'gk',pct:73,topics:['Türkiye Gündemi','Bilim ve Teknoloji','Kültür ve Sanat','Uluslararası Kuruluşlar','Ekonomi']}];
const bank=Array.isArray(window.KPSS_BANK)?window.KPSS_BANK:[];
let state={correct:0,wrong:0,answered:0,wrongs:[],favorites:[],later:[],xp:0,planDone:[]};
try{Object.assign(state,JSON.parse(localStorage.getItem('kpssState')||'null')||{})}catch{}
const save=()=>{try{localStorage.setItem('kpssState',JSON.stringify(state))}catch{}};
let subject='Matematik',topic='',qi=0,choice=null,answered=false,qt=null,examSize=120,ei=0,ea=[],eq=[],examStart=0,et=null;
const plans=[['Matematik','Problemler • 20 soru','Soru çözümü'],['Türkçe','Paragraf • 15 soru','Hızlı okuma'],['Tarih','Osmanlı • 10 soru','Konu tekrarı'],['Genel tekrar','Yanlışlar • 10 soru','Tekrar']];
function toast(t){const x=$('toast');if(x){x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),1600)}}
function timers(){clearInterval(qt);clearInterval(et);qt=et=null}
function show(id){timers();document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.bottom button').forEach(x=>x.classList.toggle('on',x.dataset.go===id));({home,subjects:renderSubjects,topic:renderTopics,question:renderQuestion,exams:renderExams,examrun:renderExam,result:()=>{},wrongs:renderWrongs,stats:renderStats,profile:renderProfile,past:renderPast,plan:renderPlan}[id]||home)()}
function home(){const n=Math.min(50,state.answered||0),p=Math.round(n/50*100);if($('goalCount'))$('goalCount').innerHTML=n+' <span>/ 50 soru</span>';if($('goalPct'))$('goalPct').textContent='%'+p;if($('goalBar'))$('goalBar').style.width=p+'%';if($('ring'))$('ring').style.background='conic-gradient(#24dcb8 '+p+'%,#263b4e 0)';if($('todayWork'))$('todayWork').innerHTML=subjectData.slice(1,4).map(s=>'<div class="workrow"><span class="mini '+s.tone+'">'+s.name[0]+'</span><span><b>'+esc(s.name)+'</b> • '+esc(s.topics[0])+'</span><em>%'+s.pct+'</em></div>').join('');if($('planProgress'))$('planProgress').textContent=state.planDone.length+' / 4 tamamlandı';if($('planBar'))$('planBar').style.width=state.planDone.length*25+'%'}
function renderSubjects(){const q=($('subjectSearch')?.value||'').toLocaleLowerCase('tr-TR'),tab=document.querySelector('#subjects .tabs button.active')?.dataset.tab||'gy',l=$('subjectList');if(!l)return;l.innerHTML=subjectData.filter(s=>s.group===tab&&(!q||s.name.toLocaleLowerCase('tr-TR').includes(q)||s.topics.some(t=>t.toLocaleLowerCase('tr-TR').includes(q)))).map((s,i)=>'<button class="subject" data-sub="'+i+'"><span class="subicon '+s.tone+'">'+s.icon+'</span><span class="subinfo"><b>'+esc(s.name)+'</b><small>'+s.topics.length+' konu • '+Math.max(21,bank.filter(x=>x.subject===s.name).length)+' soru</small></span><span class="score">%'+s.pct+'</span><span>›</span></button>').join('')}
function renderTopics(){const s=subjectData.find(x=>x.name===subject)||subjectData[1],l=$('topicList');if(!l)return;l.innerHTML=s.topics.map(t=>'<button class="topic" data-topic="'+esc(t)+'"><span class="grow"><b>'+esc(t)+'</b><small>'+bank.filter(q=>q.subject===s.name&&q.topic===t).length+' soru</small></span><span class="topicScore low">%'+Math.max(55,s.pct-s.topics.indexOf(t)*2)+'</span><span>›</span></button>').join('')}
function qlist(){const a=bank.filter(q=>q.subject===subject&&(!topic||q.topic===topic));if(a.length)return a;const b=bank.filter(q=>q.subject===subject);return b.length?b:bank}
function renderQuestion(){const a=qlist();if(!a.length)return;const q=a[qi%a.length];$('qcategory').textContent=q.subject+' • '+q.topic;$('qsubject').textContent=q.subject;$('qnum').textContent=qi+1;$('qtotal').textContent=a.length;$('qtext').textContent=q.text;$('qbar').style.width=((qi%10+1)*10)+'%';$('options').innerHTML=q.opts.map((o,i)=>'<button class="option '+(choice===i?'selected ':'')+(answered&&i===q.a?'correct ':'')+(answered&&choice===i&&i!==q.a?'wrong':'')+'" data-option="'+i+'"><span class="letter">'+String.fromCharCode(65+i)+'</span>'+esc(o)+'<span class="mark">'+(answered&&i===q.a?'✓':answered&&choice===i?'×':'')+'</span></button>').join('');$('explain').style.display=answered?'block':'none';$('explain').innerHTML=answered?'<b>Çözüm</b><p>'+esc(q.e)+'</p>':'';$('answerBtn').textContent=answered?'Sonraki Soru →':'Cevabı İşaretle';clearInterval(qt);let left=102;const tick=()=>{if($('timer'))$('timer').textContent=String(Math.floor(left/60)).padStart(2,'0')+':'+String(left%60).padStart(2,'0');if(left<=0){clearInterval(qt);toast('Süre doldu')}else left--};tick();qt=setInterval(tick,1000)}
function renderExams(){const l=$('examList');if(!l)return;l.innerHTML=[[10,15,'Hızlı Test'],[20,30,'Standart Deneme'],[30,45,'Yoğun Deneme'],[60,90,'Tam Performans'],[120,130,'Tam KPSS']].map(x=>'<button class="examrow '+(examSize===x[0]?'selected':'')+'" data-examsize="'+x[0]+'"><span class="eico">▣</span><b>'+x[2]+'<small>'+x[0]+' Soru</small></b><small>~ '+x[1]+' dakika</small><span>›</span></button>').join('')}
function startExam(){const src=bank.length?bank:[{subject:'KPSS',topic:'Genel',text:'İçerik yüklenemedi.',opts:['A','B','C','D','E'],a:0,e:''}];eq=Array.from({length:examSize},(_,i)=>src[i%src.length]);ei=0;ea=Array(examSize).fill(null);examStart=Date.now();show('examrun')}
function renderExam(){const q=eq[ei];if(!q)return;$('examNumbers').innerHTML=eq.map((_,i)=>'<span class="'+(i===ei?'current ':'')+(ea[i]!==null?'done':'')+'">'+(i+1)+'</span>').join('');$('examQnum').textContent=ei+1;$('examQtext').textContent=q.text;$('examOptions').innerHTML=q.opts.map((o,i)=>'<button class="option '+(ea[ei]===i?'selected':'')+'" data-examoption="'+i+'"><span class="letter">'+String.fromCharCode(65+i)+'</span>'+esc(o)+'</button>').join('');const c=ea.filter((a,i)=>a!==null&&a===eq[i].a).length,w=ea.filter((a,i)=>a!==null&&a!==eq[i].a).length;$('examCorrect').textContent=c;$('examWrong').textContent=w;$('examBlank').textContent=examSize-c-w;const min=examSize===10?15:examSize===20?30:examSize===30?45:examSize===60?90:130;clearInterval(et);const tick=()=>{const left=Math.max(0,min*60-Math.floor((Date.now()-examStart)/1000));$('examTimer').textContent=String(Math.floor(left/60)).padStart(2,'0')+':'+String(left%60).padStart(2,'0');if(left<=0)finishExam()};tick();et=setInterval(tick,1000)}
function finishExam(){clearInterval(et);const c=ea.filter((a,i)=>a!==null&&a===eq[i].a).length,w=ea.filter((a,i)=>a!==null&&a!==eq[i].a).length;state.correct+=c;state.wrong+=w;state.answered+=examSize;state.xp+=examSize;save();$('resultNet').textContent=(c-w/4).toFixed(2).replace('.',',');$('rCorrect').textContent=c;$('rWrong').textContent=w;$('rBlank').textContent=examSize-c-w;$('rSuccess').textContent='%'+Math.round(c/examSize*100);$('rTime').textContent=Math.max(1,Math.round((Date.now()-examStart)/60000))+' dk';show('result');toast('Deneme tamamlandı 🏆')}
function renderWrongs(){const l=$('wrongList');if(!l)return;l.innerHTML=state.wrongs.length?state.wrongs.map((w,i)=>'<section class="card"><small>Yanlış soru '+(i+1)+'</small><h3>'+esc(w.text)+'</h3><button class="primary" data-retry="'+i+'">Tekrar Çöz</button></section>').join(''):'<section class="card"><b>Harika! 🎉</b><p class="muted">Henüz yanlış kaydın yok.</p></section>'}
function renderStats(){const n=state.answered||0;$('totalQ').textContent=n;$('success').textContent='%'+(n?Math.round((state.correct||0)/n*100):0);$('net').textContent=((state.correct||0)-(state.wrong||0)/4).toFixed(1).replace('.',',')}
function renderProfile(){const x=state.xp||0;$('level').textContent=Math.max(1,Math.floor(x/400)+1);$('xpText').textContent=(x%2000).toLocaleString('tr-TR')+' / 2.000 XP';$('xpBar').style.width=Math.min(100,x%2000/20)+'%';$('calendar').innerHTML=Array.from({length:28},(_,i)=>'<div class="day '+(i%7===6?'active':'')+'">'+(i+1)+'<br><small>'+(i%3===0?'✓':'•')+'</small></div>').join('')}
function renderPast(){const l=$('pastList');if(!l)return;l.innerHTML=Array.from({length:16},(_,i)=>2025-i).map(y=>'<section class="card"><div class="row"><span><b>KPSS '+y+'</b><small class="muted">Resmî ÖSYM kitapçığı ve cevap anahtarı</small></span><button class="link" data-action="pastInfo">Bilgi</button></div></section>').join('')}
function renderPlan(){const l=$('planList');if(!l)return;l.innerHTML=plans.map((p,i)=>'<section class="plan"><div class="row"><b>'+esc(p[0])+'</b><button class="link" data-plan="'+i+'">'+(state.planDone.includes(i)?'Tamamlandı':'Tamamla')+'</button></div><p>'+esc(p[1])+' • '+esc(p[2])+'</p></section>').join('');$('weekPct').textContent='%'+state.planDone.length*25;$('weekBar').style.width=state.planDone.length*25+'%'}
function modal(t,b){$('modalTitle').textContent=t;$('modalBody').innerHTML=b;$('modal').classList.add('open')}
function act(n){if(n==='startExam')return startExam();if(n==='examPrev'){if(ei){ei--;renderExam()}return}if(n==='examNext'){if(ei<examSize-1){ei++;renderExam()}else finishExam();return}if(n==='favorite'){state.favorites.push(qi);save();return toast('Favorilere eklendi')}if(n==='later'){state.later.push(qi);save();return toast('Sonra çöz listesine eklendi')}if(n==='explain'){const q=qlist()[qi%qlist().length];return modal('Çözüm','<p>'+esc(q.e)+'</p>')}if(n==='clearWrongs'){state.wrongs=[];save();return renderWrongs()}if(n==='closeModal')return $('modal').classList.remove('open');if(n==='confirmExit')return show('exams');if(n==='resetExam'){examSize=120;return renderExams()}if(n==='focusSearch')return $('subjectSearch')?.focus();if(n==='settings')return modal('Ayarlar','<p>İlerleme cihazında saklanır.</p>');if(n==='allBadges')return modal('Rozetler','<p>Çalışmaya devam ettikçe rozetlerin açılır. 🏆</p>');if(n==='pastInfo')return modal('ÖSYM arşivi','<p>Çıkmış sorular telifli olduğu için uygulama içinde kopyalanmaz; resmî ÖSYM kaynağı kullanılmalıdır.</p>');if(n==='resultAnalysis')return show('stats');if(n==='reviewExam')return show('examrun');if(n==='share')return toast('Sonuç paylaşımı hazır');if(n==='topicStats'||n==='topicNotes')return modal('Bilgi','<p>Bu bölüm sonraki içerik güncellemesinde genişletilecek.</p>');if(n==='editPlan')return toast('Plan düzenleme hazır');if(n==='notify')return modal('Bildirimler','<p>Yeni bildirim yok. 🔔</p>');if(n==='period'||n==='statsSubjects'||n==='statsTopics')return toast('İstatistik görünümü hazır')}
function click(e){const go=e.target.closest('[data-go]');if(go){e.preventDefault();show(go.dataset.go);return}const sub=e.target.closest('[data-sub]');if(sub){const s=subjectData[+sub.dataset.sub];if(s){subject=s.name;topic='';$('topicTitle').textContent=s.name;$('topicName').textContent=s.name;$('topicMeta').textContent=s.topics.length+' konu';show('topic')}return}const tp=e.target.closest('[data-topic]');if(tp){topic=tp.dataset.topic;qi=0;choice=null;answered=false;show('question');return}const sz=e.target.closest('[data-examsize]');if(sz){examSize=+sz.dataset.examsize||120;renderExams();return}const op=e.target.closest('[data-option]');if(op){choice=+op.dataset.option;renderQuestion();return}const eo=e.target.closest('[data-examoption]');if(eo){ea[ei]=+eo.dataset.examoption;renderExam();return}const p=e.target.closest('[data-plan]');if(p){const i=+p.dataset.plan;state.planDone=state.planDone.includes(i)?state.planDone.filter(x=>x!==i):[...state.planDone,i];save();renderPlan();home();return}const retry=e.target.closest('[data-retry]');if(retry){qi=0;choice=null;answered=false;show('question');return}const answer=e.target.closest('#answerBtn');if(answer){const a=qlist(),q=a[qi%a.length];if(answered){qi++;choice=null;answered=false}else{if(choice===null)return toast('Önce bir seçenek işaretle');answered=true;state.answered++;if(choice===q.a)state.correct++;else{state.wrong++;state.wrongs.unshift(q);state.wrongs=state.wrongs.slice(0,100)}save()}renderQuestion();return}const b=e.target.closest('[data-action]');if(b){e.preventDefault();act(b.dataset.action)}}
document.addEventListener('click',click,{passive:false});document.addEventListener('input',e=>{if(e.target.id==='subjectSearch')renderSubjects()});document.addEventListener('click',e=>{const t=e.target.closest('#subjects .tabs button');if(t){document.querySelectorAll('#subjects .tabs button').forEach(x=>x.classList.remove('active'));t.classList.add('active');renderSubjects()}});
home();window.__KPSS_RUNTIME__={show,bank,state};})();`;
function write(name,src){const h=crypto.createHash('sha256').update(src).digest('hex').slice(0,12),n=name+'.'+h+'.js';fs.writeFileSync(path.join(root,n),src);return n}
const coreName=write('app.core',core.map(f=>`\
/* ${f} */\
${fs.readFileSync(path.join(root,f),'utf8')}\
`).join(''));
const runtimeName=write('app.runtime',runtime);
let html=fs.readFileSync(indexPath,'utf8');
const all=['app.js','content.js','question-engine.js','question-bank-full.js','curriculum-expansion.js','question-bank-fixes.js','question-bank-audit.js','question-bank-complete.js','exam-content-upgrade.js','question-engine-v4.js','question-engine-v5.js','curriculum-ui.js','difficulty-ui.js','question-engine-bind.js','past.js','curriculum-subject-sync.js'];
const escaped=all.map(s=>s.replace(/[.*+?^${}()|[\\]\\\\]/g,'\\\\$&')).join('|');
html=html.replace(new RegExp(`<script(?:\\s+defer)?\\s+src=["'](?:${escaped})["']\\s*><\\/script>`,'g'),'');
html=html.replace(/<script>\\s*\\(\\(\\)=>\\{[\\s\\S]*?\\}\\)\\(\\);\\s*<\\/script>/g,'');
html=html.replace('</body>',`<script defer src="${coreName}"></script><script defer src="${runtimeName}"></script></body>`);
fs.writeFileSync(indexPath,html);
console.log('KPSS-Mobil single-runtime build: '+coreName+' + '+runtimeName);
