/* KPSS-Mobil — full curriculum + 10 benzersiz konu testi */
(function(){
'use strict';
const C=window.KPSS_CURRICULUM||{};const bank=()=>Array.isArray(window.KPSS_BANK)?window.KPSS_BANK:[];
const norm=s=>String(s||'').toLocaleLowerCase('tr-TR').replace(/[-–—]/g,' ').replace(/\s+/g,' ').trim();const topics=s=>(C[s]||[]);
const TEST_COUNT=10,TEST_SIZE=20;
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.bottom button').forEach(b=>b.classList.toggle('on',b.dataset.go===id));}
function pool(subject,topic){const key=subject+'|'+topic,tests=window.KPSS_TOPIC_TESTS&&window.KPSS_TOPIC_TESTS[key];if(Array.isArray(tests)&&tests.length===TEST_COUNT)return tests.flat().filter(q=>Array.isArray(q.opts)&&q.opts.length===5);return bank().filter(q=>norm(q.subject)===norm(subject)&&norm(q.topic)===norm(topic)&&q.source!=='generated-practice'&&Array.isArray(q.opts)&&q.opts.length===5);}
function openTestPicker(subject,topic){let old=document.getElementById('topicTestPicker');if(old)old.remove();const available=pool(subject,topic).length,ready=available>=TEST_COUNT*TEST_SIZE;const wrap=document.createElement('div');wrap.id='topicTestPicker';wrap.innerHTML=`<div class="topic-picker-backdrop"><div class="topic-picker-card"><button class="topic-picker-close" data-close-topic-picker>×</button><div class="eyebrow">KONU TESTİ</div><h3>${topic}</h3>${ready?`<p>${available} benzersiz doğrulanmış soru • ${TEST_COUNT} test × ${TEST_SIZE} soru</p><div class="topic-test-grid">${Array.from({length:TEST_COUNT},(_,i)=>i+1).map(n=>`<button data-topic-test="${n}"><b>Test ${n}</b><small>${TEST_SIZE} soru • doğrulanmış içerik</small><span>Başla ›</span></button>`).join('')}</div>`:`<div class="content-lock"><b>⏳ Bu konu henüz teste açılmadı.</b><p>Yapay tekrar soruları kullanılmıyor. ${TEST_COUNT} testin açılması için ${TEST_COUNT*TEST_SIZE} benzersiz doğrulanmış soru gerekiyor.</p></div>`}</div></div>`;document.body.appendChild(wrap);wrap.querySelectorAll('[data-topic-test]').forEach(b=>b.addEventListener('click',()=>{const n=Number(b.dataset.topicTest);wrap.remove();start(subject,topic,n)}));wrap.querySelector('[data-close-topic-picker]').addEventListener('click',()=>wrap.remove());}
function renderTopic(subject){const list=document.getElementById('topicList');if(!list)return;const ts=topics(subject);document.getElementById('topicTitle').textContent=subject;document.getElementById('topicName').textContent=subject;document.getElementById('topicMeta').textContent=`${ts.length} konu • ${TEST_COUNT} testlik benzersiz soru havuzu`;list.innerHTML=ts.map(t=>{const n=pool(subject,t).length;return `<button class="topic" data-full-topic="${encodeURIComponent(subject)}|${encodeURIComponent(t)}"><span class="grow"><b>${t}</b><small>${n>=TEST_COUNT*TEST_SIZE?`${TEST_COUNT} test • ${TEST_COUNT*TEST_SIZE} benzersiz soru • ${TEST_SIZE}/test`:'İçerik hazırlanıyor • test kilitli'}</small></span><span class="topicScore">${n>=TEST_COUNT*TEST_SIZE?TEST_COUNT:n+' soru'}</span><span>›</span></button>`}).join('');show('topic');}
let session=null,pos=0,chosen=null,locked=false;
function start(subject,topic,testNo=1){const tests=window.KPSS_TOPIC_TESTS&&window.KPSS_TOPIC_TESTS[subject+'|'+topic];if(!Array.isArray(tests)||tests.length!==TEST_COUNT){show('topic');return}const idx=Math.max(1,Math.min(TEST_COUNT,Number(testNo)||1))-1;session=tests[idx].slice(0,TEST_SIZE);if(session.length<TEST_SIZE){show('topic');return}pos=0;chosen=null;locked=false;show('question');render();}
function render(){const q=session&&session[pos];if(!q)return;document.getElementById('qtotal').textContent=session.length;document.getElementById('qnum').textContent=pos+1;document.getElementById('qcategory').textContent=q.subject+' • '+q.topic;document.getElementById('qsubject').textContent=q.subject;document.getElementById('qtext').textContent=q.text;document.getElementById('qbar').style.width=((pos+1)/session.length*100)+'%';document.getElementById('options').innerHTML=q.opts.map((o,i)=>`<button class="option ${chosen===i?'selected':''} ${locked&&i===q.a?'correct':''} ${locked&&chosen===i&&chosen!==q.a?'wrong':''}" data-curr-option="${i}"><span class="letter">${String.fromCharCode(65+i)}</span>${o}<span class="mark">${locked&&i===q.a?'✓':locked&&chosen===i?'×':''}</span></button>`).join('');document.getElementById('answerBtn').textContent=locked?'Sonraki Soru →':'Cevabı İşaretle';const ex=document.getElementById('explain');ex.style.display=locked?'block':'none';ex.innerHTML=locked?`<b>Çözüm</b><p>${q.e||'Doğru cevap işaretli seçenektir.'}</p>`:'';}
function answer(){if(!session)return;const q=session[pos];if(!locked){if(chosen===null)return;locked=true;try{const s=JSON.parse(localStorage.getItem('kpssState')||'{}');s.correct=Number(s.correct||0)+(chosen===q.a?1:0);s.wrong=Number(s.wrong||0)+(chosen===q.a?0:1);s.answered=Number(s.answered||0)+1;s.xp=Number(s.xp||0)+10;s.byTopic=s.byTopic||{};s.byTopic[q.topic]=s.byTopic[q.topic]||{correct:0,wrong:0,answered:0};s.byTopic[q.topic].answered++;s.byTopic[q.topic][chosen===q.a?'correct':'wrong']++;if(chosen!==q.a){s.wrongs=s.wrongs||[];s.wrongs.unshift(q)}localStorage.setItem('kpssState',JSON.stringify(s))}catch(e){}render();return}pos++;chosen=null;locked=false;if(pos>=session.length){session=null;show('subjects');if(window.renderSubjects)window.renderSubjects();return}render();}
document.addEventListener('click',function(e){const t=e.target.closest('[data-full-topic]');if(t){e.preventDefault();e.stopImmediatePropagation();const [s,x]=t.dataset.fullTopic.split('|').map(decodeURIComponent);openTestPicker(s,x);return}const o=e.target.closest('[data-curr-option]');if(o){e.preventDefault();e.stopImmediatePropagation();chosen=Number(o.dataset.currOption);render();return}const a=e.target.closest('#answerBtn');if(a&&session){e.preventDefault();e.stopImmediatePropagation();answer();return}const sub=e.target.closest('[data-sub]');if(sub&&window.KPSS_CURRICULUM){e.preventDefault();e.stopImmediatePropagation();const subjects=['Türkçe','Matematik','Tarih','Coğrafya','Vatandaşlık','Güncel Bilgiler'];renderTopic(subjects[Number(sub.dataset.sub)]||subjects[0]);return}},true);
window.KPSS_FULL_CURRICULUM=C;window.KPSS_TOPIC_TEST=start;window.renderFullTopics=renderTopic;
})();
