(()=>{
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const LESSONS={
'Sözcükte Anlam':{icon:'Aa',tag:'Temel Kavramlar',summary:'Bir sözcüğün anlamını tek başına değil, kullanıldığı cümle ve bağlama göre belirle. KPSS’de gerçek, mecaz, terim ve yan anlam ayrımı sık ölçülür.',key:['Gerçek anlam: Sözcüğün temel anlamı.','Mecaz anlam: Gerçek anlamdan uzaklaşarak kazanılan anlam.','Terim anlam: Bir bilim, sanat veya meslek alanına özgü anlam.'],example:'“Bu sözler kalbimi kırdı.” → “kırdı” mecaz anlamdadır.',tip:'Şıkta yalnızca sözcüğe değil, sözcüğün cümlede kazandığı anlama bak.'},
'Cümlede Anlam':{icon:'C',tag:'Yargı ve İlişkiler',summary:'Cümlede verilen yargıyı ve yargılar arasındaki ilişkiyi belirle. Neden-sonuç, amaç-sonuç, koşul, karşılaştırma ve çıkarım sorularını ayır.',key:['Neden-sonuç: “Niçin?” sorusuna cevap verir.','Amaç-sonuç: Bir hedef için yapılan işi gösterir.','Koşul: Bir durumun gerçekleşmesini başka bir duruma bağlar.'],example:'“Başarılı olmak için düzenli çalışıyor.” → amaç-sonuç.',tip:'Soru kökündeki kesinlik, olasılık, amaç ve neden ifadelerini özellikle kontrol et.'},
'Paragraf':{icon:'¶',tag:'Okuma ve Yorum',summary:'Paragrafın tamamını okuyarak konu, ana düşünce, yardımcı düşünce ve çıkarımı belirle. Cevabı metnin dışındaki bilgiden değil, metinden çıkar.',key:['Konu: Paragrafın ne hakkında olduğu.','Ana düşünce: Yazarın asıl vermek istediği mesaj.','Yardımcı düşünce: Ana düşünceyi destekleyen ayrıntılar.'],example:'Ana düşünce sorusunda en kapsamlı ve metnin tamamını karşılayan yargıyı ara.',tip:'“Değinilmemiştir” ve “çıkarılamaz” gibi soru köklerini atlama.'},
'Dil Bilgisi':{icon:'A+',tag:'Kural Uygulama',summary:'Sözcük türleri, fiilimsi, cümlenin ögeleri ve yapı bilgisi gibi konuları kuralı cümle üzerinde uygulayarak öğren.',key:['Önce yüklemi belirle.','Sözcüğün görevini cümledeki kullanımına göre değerlendir.','Fiilimsi ile çekimli fiili ayır.'],example:'“Koşarak eve geldi.” → “koşarak” zarf-fiildir.',tip:'Ezberden çok örnek cümle üzerinden çözüm yap.'},
'Yazım Kuralları':{icon:'Aa',tag:'Doğru Yazım',summary:'Büyük harf, ayrı-bitişik yazım, özel adlar ve bağlaçların kullanımını örneklerle pekiştir.',key:['Bağlaç olan de/da ayrı yazılır.','Özel adlar büyük harfle başlar.','Birleşik sözcüklerde ayrı-bitişik yazım kurala göre değerlendirilir.'],example:'“Ben de geleceğim.” → “de” bağlaçtır ve ayrı yazılır.',tip:'Şıklardaki yazımı tek tek kontrol et; kulağa doğru gelmesine güvenme.'},
'Noktalama':{icon:'?!',tag:'İşaretlerin Görevi',summary:'Noktalama işaretinin cümlede hangi görevi üstlendiğini belirle. Özellikle virgül, iki nokta, noktalı virgül ve kesme işaretini ayırt et.',key:['Virgül: Eş görevli ögeleri ve bazı ara sözleri ayırır.','İki nokta: Açıklama veya örnekten önce kullanılabilir.','Kesme: Özel adlara gelen bazı ekleri ayırır.'],example:'“Çantamda üç şey var: kitap, kalem, defter.” → açıklama öncesi iki nokta.',tip:'İşareti ezberlemek yerine “Burada hangi görevi görüyor?” diye sor.'}
};
function data(topic){return LESSONS[topic]||{icon:'•',tag:'KPSS Konu Dersi',summary:`${topic} konusunun temel kavramlarını öğren, örneklerle pekiştir ve ardından konu testini çöz.`,key:['Temel kavramları öğren.','Kuralları örnekler üzerinden uygula.','Soru kökündeki kritik ifadeleri işaretle.'],example:'Öğrendikten sonra hemen birkaç soru çözerek bilgiyi pekiştir.',tip:'Yanlış yaptığın sorunun nedenini not al ve tekrar et.'}}
function enhance(){const modal=$('modal'),body=$('modalBody');if(!modal||!body||!modal.classList.contains('open'))return;const title=$('modalTitle')?.textContent||'';const topic=title.replace(/\s*•\s*Ders\s*$/,'').trim();if(!topic)return;const d=data(topic);body.innerHTML=`<div class="lessonPro">
<div class="lessonHero"><span class="lessonIcon">${esc(d.icon)}</span><div><span class="lessonTag">${esc(d.tag)}</span><h3>${esc(topic)}</h3><p>${esc(d.summary)}</p></div></div>
<div class="lessonBlock"><div class="lessonBlockTitle"><span>◆</span>Kilit Bilgiler</div><div class="lessonKeys">${d.key.map((x,i)=>`<div><b>${i+1}</b><span>${esc(x)}</span></div>`).join('')}</div></div>
<div class="lessonExample"><span>ÖRNEK</span><p>${esc(d.example)}</p></div>
<div class="lessonTip"><span>💡</span><p><b>Sınav İpucu</b><br>${esc(d.tip)}</p></div>
<button class="primary lessonStart" id="startTopicTest">Konu Testini Başlat <span>→</span></button>
<button class="lessonClose" type="button" data-lesson-close>Kapat</button>
</div>`;
const start=$('startTopicTest');start?.addEventListener('click',()=>{modal.classList.remove('open');const target=[...document.querySelectorAll('#topicList [data-topic]')].find(x=>decodeURIComponent(x.dataset.topic||'')===topic);if(target){window.__KPSS_ALLOW_TOPIC_CLICK__=true;target.click()}});
body.querySelector('[data-lesson-close]')?.addEventListener('click',()=>modal.classList.remove('open'));
}
const obs=new MutationObserver(enhance);obs.observe(document.documentElement,{subtree:true,attributes:true,attributeFilter:['class']});
const st=document.createElement('style');st.textContent=`
/* Compact professional lesson experience */
#modal{align-items:flex-end!important;padding:0!important;background:rgba(0,4,12,.72)!important;backdrop-filter:blur(9px)}
#modal .sheet{width:min(100%,390px)!important;max-height:min(84vh,720px)!important;margin:0!important;border:1px solid rgba(100,150,210,.18)!important;border-bottom:0!important;border-radius:25px 25px 0 0!important;background:linear-gradient(180deg,#0c1d31 0%,#06111e 100%)!important;box-shadow:0 -18px 50px rgba(0,0,0,.48)!important;overflow:hidden}
#modal .sheet:before{content:'';display:block;width:42px;height:4px;border-radius:9px;background:#49627c;margin:10px auto 2px;opacity:.7}
#modalTitle{display:none!important}
#modalBody{padding:10px 16px calc(16px + env(safe-area-inset-bottom))!important;overflow:auto!important}
.lessonPro{padding:0 0 2px;color:#f4f7ff}.lessonHero{display:flex;gap:13px;align-items:flex-start;padding:7px 2px 14px}.lessonIcon{width:46px;height:46px;display:grid;place-items:center;flex:0 0 46px;border-radius:15px;background:linear-gradient(145deg,#5b5cff,#3188ff);font-weight:800;font-size:17px;box-shadow:0 8px 22px #315dff55}.lessonTag{font-size:9px;letter-spacing:.8px;text-transform:uppercase;color:#79aaff;font-weight:800}.lessonHero h3{margin:3px 0 5px;font-size:22px;letter-spacing:-.4px}.lessonHero p{margin:0;color:#a9bbcf;font-size:12px;line-height:1.55}.lessonBlock{border:1px solid #1b334b;background:#091827;border-radius:17px;padding:12px 12px 9px}.lessonBlockTitle{font-size:12px;font-weight:800;margin-bottom:9px;color:#dce9f8}.lessonBlockTitle span{color:#6b74ff;margin-right:6px}.lessonKeys{display:grid;gap:8px}.lessonKeys>div{display:flex;gap:9px;align-items:flex-start}.lessonKeys b{width:20px;height:20px;display:grid;place-items:center;border-radius:7px;background:#162d46;color:#7fb4ff;font-size:10px;flex:0 0 20px}.lessonKeys span{font-size:11px;line-height:1.45;color:#b8c7d8}.lessonExample{margin-top:10px;padding:11px 12px;border-radius:15px;background:rgba(91,92,255,.09);border:1px solid rgba(91,92,255,.18)}.lessonExample span{font-size:8px;font-weight:900;letter-spacing:1px;color:#8790ff}.lessonExample p{margin:5px 0 0;font-size:11px;line-height:1.45;color:#d7e1ef}.lessonTip{display:flex;gap:9px;margin-top:10px;padding:10px 11px;border-radius:14px;background:#0c2130;border:1px solid #16384a}.lessonTip span{font-size:15px}.lessonTip p{margin:0;font-size:10px;line-height:1.45;color:#a9bfd1}.lessonTip b{color:#eaf4ff}.lessonStart{width:100%;margin-top:13px!important;height:48px!important;border-radius:15px!important;font-size:13px!important;font-weight:800!important;background:linear-gradient(100deg,#5757ff,#3289ff)!important;box-shadow:0 10px 24px #315dff42!important}.lessonStart span{margin-left:5px}.lessonClose{display:block;width:100%;border:0;background:none;color:#9eb0c3;font-size:12px;padding:11px 0 3px}.lessonClose:active{color:#fff}
@media(min-width:700px){#modal .sheet{border-radius:25px!important;border-bottom:1px solid rgba(100,150,210,.18)!important;margin-bottom:20px!important}}
`;document.head.appendChild(st);
setTimeout(enhance,50);setTimeout(enhance,250);
})();
