/* KPSS-Mobil Question Engine v3 — ders/konu uyumlu özgün soru sistemi */
(function(){
'use strict';
const base=(window.KPSS_CONTENT&&window.KPSS_CONTENT.questions||[]).map(q=>({subject:q[0],topic:q[1],text:q[2],opts:q[3],a:q[4],e:q[5]}));
const extra=[
{subject:'Türkçe',topic:'Sözcükte Anlam',text:'“Bu sözleriyle konuyu kapattı.” cümlesinde “kapattı” sözcüğü hangi anlamda kullanılmıştır?',opts:['Gerçek','Mecaz','Terim','Yan anlam','Somut'],a:1,e:'Burada fiziksel olarak kapatma değil, konuyu sona erdirme anlamı vardır; sözcük mecaz anlamdadır.'},
{subject:'Türkçe',topic:'Cümlede Anlam',text:'Aşağıdakilerden hangisinde karşılaştırma yapılmıştır?',opts:['Bugün erkenden uyandı.','Bu kitap diğerinden daha akıcı.','Sınava yarın girecek.','Soruyu dikkatle çözdü.','Kütüphaneye gitti.'],a:1,e:'“Daha akıcı” ifadesi iki kitabı karşılaştırmaktadır.'},
{subject:'Türkçe',topic:'Paragraf',text:'Bir paragrafta düşüncenin örneklerle desteklenmesi hangi anlatım yoluna örnektir?',opts:['Tanımlama','Örneklendirme','Benzetme','Tanık gösterme','Sayısal veri'],a:1,e:'Bir düşünceyi somutlaştırmak için örneklerden yararlanılması örneklendirmedir.'},
{subject:'Türkçe',topic:'Dil Bilgisi',text:'“Güzel ev” söz grubunda “güzel” sözcüğünün türü nedir?',opts:['Zarf','Sıfat','Zamir','Edat','Bağlaç'],a:1,e:'“Güzel”, “ev” adını nitelediği için sıfattır.'},
{subject:'Türkçe',topic:'Yazım Kuralları',text:'Aşağıdakilerden hangisinin yazımı doğrudur?',opts:['Herşey','Bir çok','Pekçok','Hiçbir','Bir kaç'],a:3,e:'“Hiçbir” bitişik yazılır.'},
{subject:'Türkçe',topic:'Noktalama',text:'“Ali, Ayşe ve Mehmet geldi.” cümlesinde virgülün görevi nedir?',opts:['Ara sözü ayırmak','Eş görevli sözcükleri ayırmak','Hitabı belirtmek','Alıntıyı göstermek','Ünlemi belirtmek'],a:1,e:'Virgül burada sıralanan eş görevli kişi adlarını ayırmaktadır.'},
{subject:'Matematik',topic:'Bölme - Bölünebilme',text:'756 sayısı aşağıdakilerden hangisine tam bölünür?',opts:['4','5','7','9','11'],a:0,e:'Son iki basamak 56 olduğu için 4’e tam bölünür.'},
{subject:'Matematik',topic:'Kümeler',text:'A={1,2,3,4}, B={3,4,5} ise A∩B nedir?',opts:['{1,2}','{3,4}','{1,2,3,4,5}','{5}','∅'],a:1,e:'Kesişimde iki kümede ortak bulunan elemanlar yer alır: {3,4}.'},
{subject:'Matematik',topic:'Fonksiyon',text:'f(x)=2x+3 ise f(4) kaçtır?',opts:['7','8','10','11','12'],a:3,e:'f(4)=2·4+3=11.'},
{subject:'Matematik',topic:'Permütasyon',text:'4 farklı kitap bir rafa kaç farklı şekilde dizilebilir?',opts:['4','8','12','16','24'],a:4,e:'4 farklı nesnenin sıralanışı 4!=24’tür.'},
{subject:'Matematik',topic:'Geometri',text:'Dikdörtgenin kenarları 6 cm ve 4 cm ise alanı kaç cm²dir?',opts:['10','20','24','28','40'],a:2,e:'Alan=6×4=24 cm².'},
{subject:'Matematik',topic:'Tablo ve Grafikler',text:'Bir grafikte 2024 satışları 80, 2025 satışları 100 ise artış yüzde kaçtır?',opts:['10','20','25','30','40'],a:2,e:'Artış 20’dir. 20/80×100=%25.'},
{subject:'Tarih',topic:'Osmanlı Kuruluş',text:'Osmanlı Devleti’nde Rumeli’ye geçişi sağlayan gelişme hangisidir?',opts:['İstanbul’un fethi','Çimpe Kalesi’nin alınması','Ankara Savaşı','Kösedağ Savaşı','Mohaç Savaşı'],a:1,e:'Çimpe Kalesi’nin alınması Osmanlıların Rumeli’deki ilk önemli dayanaklarından biridir.'},
{subject:'Tarih',topic:'Osmanlı Kültür',text:'Osmanlılarda devşirme sisteminden yetişen askerî sınıf aşağıdakilerden hangisidir?',opts:['Reaya','Kapıkulu','Ayan','Lonca','Tımar sahibi'],a:1,e:'Devşirme sistemi özellikle Kapıkulu teşkilatına insan kaynağı sağlamıştır.'},
{subject:'Tarih',topic:'Cumhuriyet Dönemi',text:'Saltanat hangi tarihte kaldırılmıştır?',opts:['19 Mayıs 1919','23 Nisan 1920','1 Kasım 1922','29 Ekim 1923','3 Mart 1924'],a:2,e:'Saltanat 1 Kasım 1922’de kaldırılmıştır.'},
{subject:'Tarih',topic:'Atatürk İlkeleri',text:'Toplumda ayrıcalık ve sınıf farklılıklarını reddeden ilke hangisidir?',opts:['Halkçılık','Devletçilik','Laiklik','İnkılapçılık','Milliyetçilik'],a:0,e:'Halkçılık, kanun önünde eşitlik ve ayrıcalıksız toplum anlayışını vurgular.'},
{subject:'Tarih',topic:'Türk Kültür ve Medeniyetleri',text:'Türklerin İslamiyet’i kabulünden sonra kurduğu ilk büyük devletlerden biri hangisidir?',opts:['Karahanlılar','Göktürkler','Hunlar','Uygurlar','Avarlar'],a:0,e:'Karahanlılar, İslamiyet’i kabul eden ilk Türk devletleri arasında yer alır.'},
{subject:'Coğrafya',topic:'Türkiye Fiziki Coğrafyası',text:'Türkiye’nin en uzun akarsuyu hangisidir?',opts:['Kızılırmak','Fırat','Dicle','Sakarya','Yeşilırmak'],a:0,e:'Türkiye sınırları içindeki en uzun akarsu Kızılırmak’tır.'},
{subject:'Coğrafya',topic:'İklim',text:'İç Anadolu’da doğal bitki örtüsünün bozkır olmasında hangisi etkilidir?',opts:['Yıllık yağışın az olması','Nem oranının çok yüksek olması','Sürekli kar yağışı','Gelgitler','Muson rüzgârları'],a:0,e:'İç kesimlerde yağışın görece az olması bozkırın yaygınlaşmasında etkilidir.'},
{subject:'Coğrafya',topic:'Nüfus',text:'Bir yerleşmede doğum ve ölüm oranlarının nüfus üzerindeki etkisini inceleyen temel konu hangisidir?',opts:['Nüfusun doğal artışı','Sanayi dağılışı','Madenler','İklim','Toprak türleri'],a:0,e:'Doğumlar ile ölümler arasındaki fark doğal nüfus artışını belirler.'},
{subject:'Coğrafya',topic:'Ekonomik Coğrafya',text:'Türkiye’de sanayinin gelişmesinde aşağıdakilerden hangisi doğrudan etkili bir faktördür?',opts:['Ham madde ve ulaşım olanakları','Enlem farkının olmaması','Güneş tutulmaları','Gelgit genliği','Dünya’nın eksen eğikliği'],a:0,e:'Ham maddeye, pazara ve ulaşım ağlarına erişim sanayinin yer seçiminde önemlidir.'},
{subject:'Coğrafya',topic:'Bölgeler',text:'Çay tarımının Türkiye’de en yoğun yapıldığı bölüm hangisidir?',opts:['Doğu Karadeniz','Ergene','Konya','Güneydoğu Toroslar','Teke'],a:0,e:'Çay, nemli iklim koşulları nedeniyle özellikle Doğu Karadeniz’de yetiştirilir.'},
{subject:'Vatandaşlık',topic:'Hukukun Temelleri',text:'Hukuk kurallarını diğer toplumsal düzen kurallarından ayıran temel özelliklerden biri nedir?',opts:['Devlet yaptırımının bulunması','Sadece gelenek olması','Her zaman yazısız olması','Kişisel tercihe bağlı olması','Sadece aile içinde uygulanması'],a:0,e:'Hukuk kuralları devlet gücüyle desteklenen yaptırımlara bağlanmıştır.'},
{subject:'Vatandaşlık',topic:'Anayasa',text:'Türkiye Cumhuriyeti’nin yönetim şekli Anayasa’ya göre nedir?',opts:['Monarşi','Cumhuriyet','Teokrasi','Federasyon','Konfederasyon'],a:1,e:'Anayasa’nın 1. maddesine göre Türkiye Devleti bir Cumhuriyettir.'},
{subject:'Vatandaşlık',topic:'Yasama',text:'TBMM kaç milletvekilinden oluşur?',opts:['450','500','550','600','650'],a:3,e:'Anayasa’ya göre TBMM genel olarak 600 milletvekilinden oluşur.'},
{subject:'Vatandaşlık',topic:'Yürütme',text:'Yürütme yetkisi ve görevi kim tarafından kullanılır ve yerine getirilir?',opts:['TBMM','Cumhurbaşkanı','Anayasa Mahkemesi','Yargıtay','Danıştay'],a:1,e:'Anayasa sisteminde yürütme yetkisi ve görevi Cumhurbaşkanı tarafından kullanılır ve yerine getirilir.'},
{subject:'Vatandaşlık',topic:'Yargı',text:'Anayasa Mahkemesi kaç üyeden oluşur?',opts:['11','13','15','17','21'],a:2,e:'Anayasa Mahkemesi 15 üyeden oluşur.'},
{subject:'Vatandaşlık',topic:'İdare Hukuku',text:'İl genel idaresinin başı kimdir?',opts:['Belediye başkanı','Vali','Kaymakam','Muhtar','İl genel meclisi başkanı'],a:1,e:'İl genel idaresinin başı validir.'},
{subject:'Güncel Bilgiler',topic:'Türkiye Gündemi',text:'Türkiye’nin para birimi hangisidir?',opts:['Euro','Dolar','Türk lirası','Sterlin','Frank'],a:2,e:'Türkiye’nin resmî para birimi Türk lirasıdır.'},
{subject:'Güncel Bilgiler',topic:'Dünya Gündemi',text:'Birleşmiş Milletler’in merkezi hangi şehirdedir?',opts:['New York','Paris','Roma','Tokyo','Berlin'],a:0,e:'Birleşmiş Milletler’in ana merkezi New York’tadır.'},
{subject:'Güncel Bilgiler',topic:'Bilim ve Teknoloji',text:'İnternette web sayfalarının aktarımında kullanılan temel protokollerden biri hangisidir?',opts:['HTTP','JPEG','MP3','PNG','PDF'],a:0,e:'HTTP, web istemcileri ile sunucuları arasında veri aktarımı için kullanılan protokoldür.'},
{subject:'Güncel Bilgiler',topic:'Kültür ve Sanat',text:'Nobel Edebiyat Ödülü hangi alandaki başarıları ödüllendirir?',opts:['Edebiyat','Mimarlık','Spor','Astronomi','Mühendislik'],a:0,e:'Nobel Edebiyat Ödülü edebiyat alanındaki üstün çalışmaları ödüllendirir.'},
{subject:'Güncel Bilgiler',topic:'Spor',text:'Futbolda bir takım sahada normal olarak kaç oyuncuyla yer alır?',opts:['9','10','11','12','13'],a:2,e:'Bir futbol takımının sahadaki oyuncu sayısı 11’dir.'},
{subject:'Güncel Bilgiler',topic:'Ekonomi',text:'GSYH kısaltması hangi kavramı ifade eder?',opts:['Gayrisafi yurt içi hasıla','Genel sosyal yardım haritası','Gayrisafi yıllık harcama','Genel sermaye yatırım hesabı','Gümrük satış yükü'],a:0,e:'GSYH, bir ülke sınırları içinde belirli dönemde üretilen nihai mal ve hizmetlerin parasal değerini ifade eder.'}
];
const bank=base.concat(extra);
const norm=s=>String(s||'').toLocaleLowerCase('tr-TR').replace(/[–—]/g,'-').replace(/\s+/g,' ').trim();
const aliases={
 'bölme - bölünebilme':['bölme-bölünebilme','bölme - bölünebilme'],
 'fiziki coğrafya':['türkiye fiziki coğrafyası','fiziki coğrafya'],
 'türk kültür ve medeniyetleri':['türk kültür ve medeniyetleri'],
 'tablo ve grafikler':['tablo, grafik okuma ve yorumlama','tablo ve grafikler'],
 'idare hukuku':['idare','idare hukuku']
};
function topicMatch(a,b){const x=norm(a),y=norm(b);if(x===y)return true;for(const k in aliases){if((x===k||aliases[k].some(v=>norm(v)===x))&&(y===k||aliases[k].some(v=>norm(v)===y)))return true}return x.includes(y)||y.includes(x)}
window.KPSS_BANK=bank;
window.KPSS_BANK_INFO={total:bank.length,subjects:[...new Set(bank.map(q=>q.subject))],topics:[...new Set(bank.map(q=>q.topic))],version:'3.0.0'};
let qi=0,choice=null,answered=false,exam=[],ei=0,answers=[],examSize=10,examStarted=0,examDuration=900;
const defaultState={correct:0,wrong:0,answered:0,xp:0,wrongs:[],favorites:[],later:[],planDone:[],bySubject:{},byTopic:{}};
function state(){try{return Object.assign({},defaultState,JSON.parse(localStorage.getItem('kpssState')||'{}'))}catch{return {...defaultState}}}
function save(s){localStorage.setItem('kpssState',JSON.stringify(s))}
function toast2(t){if(typeof toast==='function')toast(t)}
function current(){return bank[qi%bank.length]}
function shuffled(a){return [...a].sort(()=>Math.random()-0.5)}
function startQuestion(index){qi=(index+bank.length)%bank.length;choice=null;answered=false;show('question');renderQuestionV3()}
function renderQuestionV3(){const q=current();document.getElementById('qcategory').textContent=q.subject+' • '+q.topic;document.getElementById('qsubject').textContent=q.subject;document.getElementById('qnum').textContent=qi+1;document.getElementById('qtotal').textContent=bank.length;document.getElementById('qtext').textContent=q.text;document.getElementById('qbar').style.width=((qi%10+1)*10)+'%';document.getElementById('options').innerHTML=q.opts.map((o,i)=>`<button class="option ${choice===i?'selected':''} ${answered&&i===q.a?'correct':''} ${answered&&choice===i&&i!==q.a?'wrong':''}" data-option="${i}"><span class="letter">${String.fromCharCode(65+i)}</span>${o}<span class="mark">${answered&&i===q.a?'✓':answered&&choice===i?'×':''}</span></button>`).join('');const ex=document.getElementById('explain');ex.style.display=answered?'block':'none';ex.innerHTML=answered?`<b>Çözüm</b><p>${q.e}</p>`:'';document.getElementById('answerBtn').textContent=answered?'Sonraki Soru →':'Cevabı İşaretle'}
window.renderQuestion=renderQuestionV3;
function answer(){if(choice===null){toast2('Önce bir seçenek işaretle');return}const q=current(),s=state();if(!answered){answered=true;s.answered=(s.answered||0)+1;s.xp=(s.xp||0)+10;s.bySubject=s.bySubject||{};s.byTopic=s.byTopic||{};const sub=s.bySubject[q.subject]||{answered:0,correct:0,wrong:0};sub.answered++;const top=s.byTopic[q.subject+'|'+q.topic]||{answered:0,correct:0,wrong:0};top.answered++;if(choice===q.a){s.correct++;sub.correct++;top.correct++;toast2('Doğru cevap! 🎯')}else{s.wrong++;sub.wrong++;top.wrong++;s.wrongs=s.wrongs||[];if(!s.wrongs.some(w=>w.text===q.text))s.wrongs.push({...q}) ;toast2('Yanlış cevap. Çözümü incele.')}s.bySubject[q.subject]=sub;s.byTopic[q.subject+'|'+q.topic]=top;save(s);renderQuestionV3();if(typeof renderHome==='function')renderHome();if(typeof renderStats==='function')renderStats()}else{qi++;choice=null;answered=false;renderQuestionV3()}}
function renderExamsV3(){const sizes=[[10,'Hızlı Test','~15 dk'],[20,'Standart Deneme','~30 dk'],[30,'Yoğun Deneme','~45 dk'],[60,'Tam Performans','~90 dk'],[120,'Tam KPSS','120 dk']];document.getElementById('examList').innerHTML=sizes.map(x=>`<button class="examrow ${examSize===x[0]?'selected':''}" data-exam-size="${x[0]}"><span class="eico">▣</span><b>${x[1]}<small>${x[0]} Soru</small></b><small>${x[2]}</small><span>›</span></button>`).join('')}
window.renderExams=renderExamsV3;
function startExamV3(size=examSize){examSize=size;examDuration=size===10?900:size===20?1800:size===30?2700:size===60?5400:7200;exam=shuffled(bank).slice(0,Math.min(size,bank.length));while(exam.length<size)exam=exam.concat(shuffled(bank).slice(0,Math.min(size-exam.length,bank.length)));ei=0;answers=Array(size).fill(null);examStarted=Date.now();show('examrun');renderExamV3();startExamClock()}
function startExamClock(){clearInterval(window.__kpExamClock);window.__kpExamClock=setInterval(()=>{const left=Math.max(0,examDuration-Math.floor((Date.now()-examStarted)/1000));const el=document.getElementById('examTimer');if(el)el.textContent=String(Math.floor(left/3600)).padStart(2,'0')+':'+String(Math.floor(left%3600/60)).padStart(2,'0')+':'+String(left%60).padStart(2,'0');if(left<=0)finishExamV3()},1000)}
function renderExamV3(){const q=exam[ei];document.getElementById('examNumbers').innerHTML=exam.map((_,i)=>`<span class="${i===ei?'current ':''}${answers[i]!==null?'done':''}" data-exam-jump="${i}">${i+1}</span>`).join('');document.getElementById('examQnum').textContent=ei+1;const meta=document.querySelector('#examrun .qmeta');if(meta)meta.innerHTML=`Soru <b>${ei+1}</b> / ${examSize}`;document.getElementById('examQtext').textContent=q.text;document.getElementById('examOptions').innerHTML=q.opts.map((o,i)=>`<button class="option ${answers[ei]===i?'selected':''}" data-examoption="${i}"><span class="letter">${String.fromCharCode(65+i)}</span>${o}</button>`).join('');const c=answers.filter((a,i)=>a!==null&&a===exam[i].a).length,w=answers.filter((a,i)=>a!==null&&a!==exam[i].a).length;document.getElementById('examCorrect').textContent=c;document.getElementById('examWrong').textContent=w;document.getElementById('examBlank').textContent=examSize-c-w}
function finishExamV3(){if(!exam.length)return;clearInterval(window.__kpExamClock);const c=answers.filter((a,i)=>a!==null&&a===exam[i].a).length,w=answers.filter((a,i)=>a!==null&&a!==exam[i].a).length,b=examSize-c-w,s=state();s.correct+=c;s.wrong+=w;s.answered+=examSize;s.xp+=Math.round(examSize*8);s.wrongs=s.wrongs||[];exam.forEach((q,i)=>{if(answers[i]!==null&&answers[i]!==q.a&&!s.wrongs.some(z=>z.text===q.text))s.wrongs.push({...q})});save(s);document.getElementById('resultNet').textContent=(c-w/4).toFixed(2).replace('.',',');document.getElementById('rCorrect').textContent=c;document.getElementById('rWrong').textContent=w;document.getElementById('rBlank').textContent=b;document.getElementById('rSuccess').textContent='%'+Math.round(c/examSize*100);document.getElementById('rTime').textContent=Math.max(1,Math.round((Date.now()-examStarted)/60000))+' dk';show('result');if(typeof renderHome==='function')renderHome();toast2('Deneme tamamlandı 🏆')}
function topicIndex(subject,topic){return bank.findIndex(q=>q.subject===subject&&topicMatch(q.topic,topic))}
function renderWrongsV3(){if(typeof renderWrongs!=='function')return;const old=window.renderWrongs;const l=document.getElementById('wrongList');const s=state(),list=s.wrongs||[];if(!list.length){l.innerHTML='<section class="card"><b>Harika! 🎉</b><p class="muted">Henüz yanlış kaydın yok.</p></section>';return}l.innerHTML=list.map((w,i)=>`<section class="card" style="margin-bottom:9px"><small>${w.subject} • ${w.topic}</small><h3 style="font-size:12px;line-height:1.5">${w.text}</h3><button class="primary" data-retry="${i}">Tekrar Çöz</button></section>`).join('')}
// Event layer runs in capture phase so the original demo handlers cannot double-fire.
document.addEventListener('click',function(e){
 const size=e.target.closest('[data-exam-size]');if(size){e.stopImmediatePropagation();examSize=Number(size.dataset.examSize);renderExamsV3();return}
 const jump=e.target.closest('[data-exam-jump]');if(jump){e.stopImmediatePropagation();ei=Math.max(0,Math.min(exam.length-1,Number(jump.dataset.examJump)));renderExamV3();return}
 const op=e.target.closest('[data-option]');if(op){e.stopImmediatePropagation();if(!answered){choice=Number(op.dataset.option);renderQuestionV3()}return}
 if(e.target.closest('#answerBtn')){e.stopImmediatePropagation();answer();return}
 const eo=e.target.closest('[data-examoption]');if(eo){e.stopImmediatePropagation();answers[ei]=Number(eo.dataset.examoption);renderExamV3();return}
 const act=e.target.closest('[data-action]');if(act){const a=act.dataset.action;if(['startExam','examNext','examPrev','favorite','later','explain'].includes(a)){e.stopImmediatePropagation();if(a==='startExam')startExamV3(examSize);else if(a==='examNext'){if(ei<examSize-1){ei++;renderExamV3()}else finishExamV3()}else if(a==='examPrev'){ei=Math.max(0,ei-1);renderExamV3()}else if(a==='favorite'){const s=state(),q=current();s.favorites=s.favorites||[];if(!s.favorites.includes(q.text))s.favorites.push(q.text);save(s);toast2('Favorilere eklendi ⭐')}else if(a==='later'){const s=state(),q=current();s.later=s.later||[];if(!s.later.includes(q.text))s.later.push(q.text);save(s);toast2('Sonra çöz listesine eklendi ⏰')}else if(a==='explain'){const x=document.getElementById('explain');x.style.display='block';x.innerHTML='<b>Çözüm</b><p>'+current().e+'</p>'}return}}
 const retry=e.target.closest('[data-retry]');if(retry){e.stopImmediatePropagation();const w=(state().wrongs||[])[Number(retry.dataset.retry)],i=bank.findIndex(q=>q.text===w?.text);if(i>=0)startQuestion(i);return}
 const tp=e.target.closest('[data-topic]');if(tp){e.stopImmediatePropagation();const subject=document.getElementById('topicName').textContent,topic=tp.dataset.topic,i=topicIndex(subject,topic);startQuestion(i>=0?i:Math.floor(Math.random()*bank.length));return}
 const goq=e.target.closest('[data-go="question"]');if(goq){e.stopImmediatePropagation();startQuestion(Math.floor(Math.random()*bank.length));return}
},true);
// Replace subject/topic counts with real bank coverage where possible.
const oldRenderTopics=window.renderTopics;
window.renderTopics=function(){if(typeof oldRenderTopics==='function')oldRenderTopics();const subject=document.getElementById('topicName')?.textContent;if(!subject)return;const list=document.getElementById('topicList');if(!list)return;const names=[...new Set(bank.filter(q=>q.subject===subject).map(q=>q.topic))];if(!names.length)return;list.innerHTML=names.map(t=>{const total=bank.filter(q=>q.subject===subject&&topicMatch(q.topic,t)).length;return `<button class="topic" data-topic="${t}"><span class="grow"><b>${t}</b><small>${total} özgün soru • konu testi</small></span><span class="topicScore">%${Math.min(99,Math.round(55+total*4))}</span><span>›</span></button>`}).join('')}
setTimeout(()=>{try{renderQuestionV3()}catch(e){}},30);
})();