// KPSS-Mobil Question Engine v3
// Özgün uygulama içeriği + ders/konu bazlı soru motoru.
(function(){
 const base=(window.KPSS_CONTENT&&window.KPSS_CONTENT.questions||[]).map(q=>({subject:q[0],topic:q[1],text:q[2],opts:q[3],a:q[4],e:q[5]}));
 const extra=window.KPSS_EXTRA||[];
 const seeds=[
 ['Türkçe','Sözcükte Anlam','“Titiz” sözcüğünün anlamca en yakın karşılığı hangisidir?',['Özensiz','Dikkatli','Kararsız','Çekingen','Dağınık'],1,'Titiz; ayrıntılara dikkat eden, özenli kimse demektir.'],
 ['Türkçe','Cümlede Anlam','“Bu kitabı okuyunca çocukluğumu hatırladım.” cümlesinde hangi anlam ilişkisi vardır?',['Karşılaştırma','Koşul','Neden-sonuç','Amaç-sonuç','Varsayım'],2,'Kitabın okunması hatırlamanın nedenidir.'],
 ['Türkçe','Paragraf','Paragrafta düşüncenin örneklerle desteklenmesinin temel amacı nedir?',['Ana düşünceyi gizlemek','Düşünceyi somutlaştırmak','Konuyu değiştirmek','Cümleleri kısaltmak','Yazarın görüşünü saklamak'],1,'Örnekler soyut düşünceleri somutlaştırır.'],
 ['Türkçe','Dil Bilgisi','“Çalışkan öğrenciler soruları dikkatle çözdü.” cümlesinde “çalışkan” sözcüğü hangi türdedir?',['Zamir','Zarf','Sıfat','Bağlaç','Edat'],2,'“Çalışkan”, öğrenciler adını nitelediği için sıfattır.'],
 ['Türkçe','Yazım Kuralları','Aşağıdakilerden hangisinin yazımı doğrudur?',['Herşey','Pekçok','Birçok','Hiç bir','Yanlız'],2,'“Birçok” bitişik yazılır.'],
 ['Türkçe','Noktalama','Soru anlamı taşıyan cümlelerin sonunda hangi işaret kullanılır?',['Virgül','Nokta','İki nokta','Soru işareti','Noktalı virgül'],3,'Soru anlamı taşıyan cümlelerin sonunda soru işareti kullanılır.'],
 ['Matematik','Temel Kavramlar','5x−10=20 olduğuna göre x kaçtır?',['4','5','6','7','8'],2,'5x=30 olduğundan x=6dır.'],
 ['Matematik','Sayılar','72 sayısının asal çarpanları hangileridir?',['2 ve 3','2 ve 5','3 ve 5','2, 3 ve 5','7 ve 9'],0,'72=2³·3² olduğundan asal çarpanları 2 ve 3’tür.'],
 ['Matematik','Bölme - Bölünebilme','Bir sayının 9 ile bölünebilmesi için hangisi gerekir?',['Son basamağı çift olmalı','Rakamları toplamı 9un katı olmalı','Son basamağı 5 olmalı','İlk basamağı 1 olmalı','Rakamları toplamı tek olmalı'],1,'9’a bölünebilme kuralında rakamlar toplamı 9’un katı olmalıdır.'],
 ['Matematik','Problemler','Bir işçi bir işi 12 günde bitiriyor. Aynı hızla 2 işçi işi kaç günde bitirir?',['3','4','6','8','10'],2,'İşçi sayısı iki katına çıkarsa süre yarıya iner: 6 gün.'],
 ['Matematik','Oran - Orantı','3:5 oranındaki iki sayının toplamı 64 ise küçük sayı kaçtır?',['18','24','28','32','40'],1,'Toplam oran 8dir. 64/8=8; küçük sayı 3×8=24.'],
 ['Matematik','Kümeler','A={1,2,3,4} kümesinin eleman sayısı kaçtır?',['2','3','4','5','6'],2,'Kümede dört farklı eleman vardır.'],
 ['Matematik','Fonksiyon','f(x)=2x+1 ise f(3) kaçtır?',['5','6','7','8','9'],2,'f(3)=2·3+1=7.'],
 ['Matematik','Permütasyon','3 farklı kitap bir rafa kaç farklı biçimde dizilebilir?',['3','6','9','12','18'],1,'3 farklı nesnenin dizilişi 3!=6dır.'],
 ['Tarih','İlk Türk Devletleri','İlk Türk devletlerinde hükümdarlık yetkisinin Tanrı tarafından verildiğine inanılan anlayış hangisidir?',['Kut','Töre','Kurultay','Ülüş','Yuğ'],0,'Kut anlayışı hükümdara yönetme yetkisinin Tanrı tarafından verildiği inancıdır.'],
 ['Tarih','Osmanlı Kuruluş','Osmanlı Devleti’nin Rumeli’deki önemli merkezlerinden Edirne hangi padişah döneminde alınmıştır?',['Osman Bey','Orhan Bey','I. Murat','II. Murat','Fatih'],2,'Edirne I. Murat döneminde alınmış ve başkent yapılmıştır.'],
 ['Tarih','Osmanlı Kültür','Osmanlılarda padişahın Divan toplantılarını izlediği bölüm hangisidir?',['Kubbealtı','Kasr-ı Adl','Kasr-ı Hümayun','Arz Odası','Enderun'],2,'Padişah Divan toplantılarını Kasr-ı Hümayun’dan takip edebilirdi.'],
 ['Tarih','Kurtuluş Savaşı','Amasya Genelgesi’nde öne çıkan temel düşünce hangisidir?',['Saltanatın güçlendirilmesi','Milli iradenin egemen olması','İstanbul’un başkent yapılması','Kapitülasyonların genişletilmesi','Ordunun dağıtılması'],1,'Amasya Genelgesi milli egemenlik ve bağımsızlık fikrini öne çıkarır.'],
 ['Tarih','Atatürk İlkeleri','“Egemenlik kayıtsız şartsız milletindir.” sözü en doğrudan hangi ilkeyle ilişkilidir?',['Devletçilik','Laiklik','Cumhuriyetçilik','İnkılapçılık','Milliyetçilik'],2,'Cumhuriyetçilik milli egemenliği esas alır.'],
 ['Tarih','Cumhuriyet Dönemi','Halifelik hangi yıl kaldırılmıştır?',['1922','1923','1924','1925','1928'],2,'Halifelik 3 Mart 1924te kaldırılmıştır.'],
 ['Coğrafya','Türkiye Fiziki Coğrafyası','Türkiye’de ortalama yükseltinin en fazla olduğu bölge hangisidir?',['Marmara','Ege','İç Anadolu','Doğu Anadolu','Akdeniz'],3,'Doğu Anadolu yüksek ve engebeli arazi yapısıyla ortalama yükseltisi en fazla bölgedir.'],
 ['Coğrafya','İklim','Akdeniz ikliminin doğal bitki örtüsü hangisidir?',['Bozkır','Maki','Tundra','Çayır','Muson'],1,'Akdeniz ikliminin doğal bitki örtüsü makidir.'],
 ['Coğrafya','Nüfus','Nüfus piramitleri öncelikle hangi özelliği gösterir?',['Maden rezervini','Yaş ve cinsiyet yapısını','Yağış miktarını','Tarım ürünlerini','Ulaşım ağını'],1,'Nüfus piramidi yaş grupları ve cinsiyet dağılımını gösterir.'],
 ['Coğrafya','Ekonomik Coğrafya','Türkiye’de çay tarımının yoğunlaştığı bölüm hangisidir?',['Doğu Karadeniz','Batı Anadolu','İç Batı Anadolu','Güneydoğu Anadolu','Ergene'],0,'Çay, Doğu Karadeniz’in nemli iklim koşullarında yetiştirilir.'],
 ['Coğrafya','Bölgeler','Türkiye’de yüz ölçümü en büyük coğrafi bölge hangisidir?',['Marmara','Ege','İç Anadolu','Doğu Anadolu','Akdeniz'],3,'Doğu Anadolu Bölgesi yüz ölçümü bakımından en büyüktür.'],
 ['Coğrafya','Harita Bilgisi','Aynı yükseltideki noktaları birleştiren çizgilere ne ad verilir?',['İzohips','İzobar','İzoterm','İzohyet','Fay'],0,'Aynı yükselti değerindeki noktaları birleştiren çizgilere izohips denir.'],
 ['Vatandaşlık','Hukukun Temelleri','Hukuk kurallarını diğer toplumsal düzen kurallarından ayıran temel özelliklerden biri hangisidir?',['Devlet yaptırımının bulunması','Sadece tavsiye olması','Sözlü olması','Kişiden kişiye değişmesi','Yaptırım içermemesi'],0,'Hukuk kuralları devlet gücüyle desteklenen yaptırımlara sahiptir.'],
 ['Vatandaşlık','Anayasa','Anayasa’nın değiştirilemez hükümleri hangi maddelerde düzenlenmiştir?',['1, 2 ve 3','2 ve 4','1, 2, 3 ve 4','5 ve 6','10 ve 11'],2,'İlk üç madde ve bunların değiştirilemeyeceğini belirten 4. madde birlikte değerlendirilir.'],
 ['Vatandaşlık','Yasama','TBMM’nin görev ve yetkilerinden biri hangisidir?',['Kanun koymak','Mahkeme kararı vermek','Vali atamak','Belediye başkanı seçmek','Merkez Bankası yönetmek'],0,'Kanun koymak, değiştirmek ve kaldırmak TBMM’nin görevlerindendir.'],
 ['Vatandaşlık','Yürütme','Yürütme yetkisi ve görevi kim tarafından kullanılır?',['TBMM','Cumhurbaşkanı','Anayasa Mahkemesi','Yargıtay','Danıştay'],1,'Yürütme yetkisi ve görevi Cumhurbaşkanı tarafından kullanılır.'],
 ['Vatandaşlık','Yargı','Anayasa Mahkemesi kaç üyeden oluşur?',['11','13','15','17','21'],2,'Anayasa Mahkemesi 15 üyeden oluşur.'],
 ['Vatandaşlık','İdare Hukuku','İlde merkezî idarenin en büyük mülki amiri kimdir?',['Belediye başkanı','Kaymakam','Vali','Muhtar','Bakan'],2,'İlde merkezî idarenin temsilcisi ve en büyük mülki amir validir.'],
 ['Güncel Bilgiler','Türkiye Gündemi','Türkiye’nin resmi para birimi hangisidir?',['Dolar','Euro','Türk lirası','Sterlin','Frank'],2,'Türkiye’nin resmi para birimi Türk lirasıdır.'],
 ['Güncel Bilgiler','Dünya Gündemi','Birleşmiş Milletler’in genel merkezi hangi şehirdedir?',['New York','Paris','Roma','Brüksel','Berlin'],0,'Birleşmiş Milletler’in genel merkezi New York’tadır.'],
 ['Güncel Bilgiler','Kurumlar','Türkiye’de yükseköğretim sisteminin düzenlenmesinde görevli üst kurul hangisidir?',['RTÜK','YÖK','BDDK','SPK','TÜİK'],1,'Yükseköğretim Kurulu (YÖK) yükseköğretim sisteminin düzenlenmesinde görev yapar.'],
 ['Güncel Bilgiler','Bilim ve Teknoloji','Kaynak kodunu hedef/çalıştırılabilir koda dönüştüren yazılım hangisidir?',['Derleyici','Tarayıcı','Router','Editör','Antivirüs'],0,'Derleyici (compiler) kaynak kodunu hedef koda dönüştürür.'],
 ['Güncel Bilgiler','Kültür ve Sanat','UNESCO’nun kültürel miras alanındaki temel amaçlarından biri hangisidir?',['Mirası korumaya katkı sağlamak','Para politikası belirlemek','Askerî ittifak kurmak','Vergi toplamak','Seçim düzenlemek'],0,'UNESCO kültürel ve doğal mirasın korunmasına yönelik iş birliğini destekler.'],
 ['Güncel Bilgiler','Spor','Olimpiyat Oyunları her bir yaz/kış döngüsü için kaç yıllık aralıkla düzenlenir?',['1','2','3','4','5'],3,'Her bir olimpiyat türünün döngüsü dört yıldır.']
 ].map(q=>({subject:q[0],topic:q[1],text:q[2],opts:q[3],a:q[4],e:q[5]}));
 const bank=[...base,...extra,...seeds]; window.KPSS_BANK=bank;
 window.KPSS_BANK_INFO={total:bank.length,subjects:[...new Set(bank.map(x=>x.subject))],topics:[...new Set(bank.map(x=>x.subject+' / '+x.topic))],version:'3.0.0'};
 let qi=0,choice=null,answered=false,examQuestions=[],examIndex=0,examAnswers=[],examStarted=0,examTimerInt=null,examLength=10;
 const read=()=>JSON.parse(localStorage.getItem('kpssState')||'{"correct":0,"wrong":0,"answered":0,"wrongs":[],"favorites":[],"later":[],"xp":0,"planDone":[]}');
 const save=s=>localStorage.setItem('kpssState',JSON.stringify(s));
 const notify=t=>typeof toast==='function'&&toast(t);
 const current=()=>bank[qi%bank.length];
 const pool=(subject,topic)=>bank.filter(x=>(!subject||x.subject===subject)&&(!topic||x.topic===topic));
 function openQuestion(i){qi=(i+bank.length)%bank.length;choice=null;answered=false;show('question');}
 window.startTopicQuestion=function(subject,topic){const p=pool(subject,topic);if(!p.length){notify('Bu konuda henüz soru bulunmuyor.');return}openQuestion(bank.indexOf(p[Math.floor(Math.random()*p.length)]));};
 window.renderQuestion=function(){const x=current();document.getElementById('qcategory').textContent=x.subject+' • '+x.topic;document.getElementById('qsubject').textContent=x.subject;document.getElementById('qnum').textContent=qi+1;document.getElementById('qtotal').textContent=bank.length;document.getElementById('qtext').textContent=x.text;document.getElementById('qbar').style.width=((qi%10+1)*10)+'%';document.getElementById('options').innerHTML=x.opts.map((o,i)=>`<button class="option ${choice===i?'selected':''} ${answered&&i===x.a?'correct':''} ${answered&&choice===i&&i!==x.a?'wrong':''}" data-option="${i}"><span class="letter">${String.fromCharCode(65+i)}</span>${o}<span class="mark">${answered&&i===x.a?'✓':answered&&choice===i?'×':''}</span></button>`).join('');const ex=document.getElementById('explain');ex.style.display=answered?'block':'none';ex.innerHTML=answered?`<b>Çözüm</b><p>${x.e}</p>`:'';document.getElementById('answerBtn').textContent=answered?'Sonraki Soru →':'Cevabı İşaretle';};
 function answer(){if(choice===null){notify('Önce bir seçenek işaretle.');return}const x=current();if(!answered){answered=true;const s=read();s.answered=(s.answered||0)+1;s.xp=(s.xp||0)+10;if(choice===x.a)s.correct=(s.correct||0)+1;else{s.wrong=(s.wrong||0)+1;s.wrongs=s.wrongs||[];if(!s.wrongs.some(w=>w.text===x.text))s.wrongs.push(x)}save(s);renderQuestion();if(typeof renderHome==='function')renderHome();if(typeof renderStats==='function')renderStats();notify(choice===x.a?'Doğru cevap! 🎯':'Yanlış cevap. Çözümü incele.')}else{openQuestion(qi+1);}}
 function beginExam(){examLength=Math.min(Math.max(Number(window.__KPSS_EXAM_LENGTH||10),10),bank.length);examQuestions=[...bank].sort(()=>Math.random()-0.5).slice(0,examLength);examIndex=0;examAnswers=Array(examLength).fill(null);examStarted=Date.now();show('examrun');startExamTimer();examRender();}
 window.beginExam=beginExam;
 function startExamTimer(){clearInterval(examTimerInt);examTimerInt=setInterval(()=>{const sec=Math.floor((Date.now()-examStarted)/1000),left=Math.max(0,examLength*90-sec),el=document.getElementById('examTimer');if(el)el.textContent=String(Math.floor(left/3600)).padStart(2,'0')+':'+String(Math.floor(left%3600/60)).padStart(2,'0')+':'+String(left%60).padStart(2,'0');if(left===0)finishExam()},1000);}
 function examRender(){const x=examQuestions[examIndex];if(!x)return;document.getElementById('examNumbers').innerHTML=examQuestions.map((_,i)=>`<span class="${i===examIndex?'current ':''}${examAnswers[i]!==null?'done':''}">${i+1}</span>`).join('');document.getElementById('examQnum').textContent=examIndex+1;document.getElementById('examQtext').textContent=x.text;document.getElementById('examOptions').innerHTML=x.opts.map((o,i)=>`<button class="option ${examAnswers[examIndex]===i?'selected':''}" data-examoption="${i}"><span class="letter">${String.fromCharCode(65+i)}</span>${o}</button>`).join('');const c=examAnswers.filter((a,i)=>a!==null&&a===examQuestions[i].a).length,w=examAnswers.filter((a,i)=>a!==null&&a!==examQuestions[i].a).length;document.getElementById('examCorrect').textContent=c;document.getElementById('examWrong').textContent=w;document.getElementById('examBlank').textContent=examLength-c-w;const qm=document.querySelector('#examrun .qmeta');if(qm)qm.innerHTML='Soru <b id="examQnum">'+(examIndex+1)+'</b> / '+examLength;}
 function finishExam(){clearInterval(examTimerInt);const c=examAnswers.filter((a,i)=>a!==null&&a===examQuestions[i].a).length,w=examAnswers.filter((a,i)=>a!==null&&a!==examQuestions[i].a).length,b=examLength-c-w,s=read();s.correct=(s.correct||0)+c;s.wrong=(s.wrong||0)+w;s.answered=(s.answered||0)+examLength;s.xp=(s.xp||0)+120;s.wrongs=s.wrongs||[];examQuestions.forEach((x,i)=>{if(examAnswers[i]!==null&&examAnswers[i]!==x.a&&!s.wrongs.some(z=>z.text===x.text))s.wrongs.push(x)});save(s);document.getElementById('resultNet').textContent=(c-w/4).toFixed(2).replace('.',',');document.getElementById('rCorrect').textContent=c;document.getElementById('rWrong').textContent=w;document.getElementById('rBlank').textContent=b;document.getElementById('rSuccess').textContent='%'+Math.round(c/examLength*100);document.getElementById('rTime').textContent=Math.max(1,Math.round((Date.now()-examStarted)/60000))+' dk';show('result');if(typeof renderHome==='function')renderHome();notify('Deneme tamamlandı 🏆');}
 function setLength(n){window.__KPSS_EXAM_LENGTH=n;document.querySelectorAll('.examrow').forEach((el,i)=>el.classList.toggle('selected',[10,20,30,60,120][i]===n));notify(n+' soruluk deneme seçildi.');}
 document.addEventListener('click',function(e){
  const op=e.target.closest('[data-option]');if(op){e.stopImmediatePropagation();if(!answered){choice=Number(op.dataset.option);renderQuestion()}return}
  const eo=e.target.closest('[data-examoption]');if(eo){e.stopImmediatePropagation();examAnswers[examIndex]=Number(eo.dataset.examoption);examRender();return}
  const b=e.target.closest('#answerBtn');if(b){e.stopImmediatePropagation();answer();return}
  const row=e.target.closest('.examrow');if(row){e.stopImmediatePropagation();const i=[...document.querySelectorAll('.examrow')].indexOf(row);setLength([10,20,30,60,120][i]);return}
  const topic=e.target.closest('[data-topic]');if(topic){e.stopImmediatePropagation();startTopicQuestion(document.getElementById('topicName').textContent,topic.dataset.topic);return}
  const go=e.target.closest('[data-go="question"]');if(go){e.stopImmediatePropagation();openQuestion(Math.floor(Math.random()*bank.length));return}
  const act=e.target.closest('[data-action]');if(act){const a=act.dataset.action;if(['favorite','later','explain','startExam','examNext','examPrev'].includes(a)){e.stopImmediatePropagation();if(a==='favorite'){const s=read();s.favorites=s.favorites||[];if(!s.favorites.includes(current().text))s.favorites.push(current().text);save(s);notify('Soru favorilere eklendi ⭐')}if(a==='later'){const s=read();s.later=s.later||[];if(!s.later.includes(current().text))s.later.push(current().text);save(s);notify('Sonra çöz listesine eklendi ⏰')}if(a==='explain'){const z=document.getElementById('explain');z.style.display='block';z.innerHTML='<b>Çözüm</b><p>'+current().e+'</p>'}if(a==='startExam')beginExam();if(a==='examNext'){if(examIndex<examLength-1){examIndex++;examRender()}else finishExam()}if(a==='examPrev'){examIndex=Math.max(0,examIndex-1);examRender()}}}
 },true);
 window.KPSS_BANK_INFO={total:bank.length,subjects:[...new Set(bank.map(x=>x.subject))],topics:[...new Set(bank.map(x=>x.subject+' / '+x.topic))],version:'3.0.0'};
 setTimeout(()=>{try{renderQuestion()}catch(e){}},50);
})();