(()=>{'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const subjectData=[
{name:'Türkçe',icon:'📖',tone:'blue',group:'gy',pct:86,topics:['Sözcükte Anlam','Cümlede Anlam','Paragraf','Dil Bilgisi','Yazım Kuralları','Noktalama']},
{name:'Matematik',icon:'▦',tone:'violet',group:'gy',pct:61,topics:['Temel Kavramlar','Sayılar','Bölme-Bölünebilme','Problemler','Oran-Orantı','Kümeler','Fonksiyon','Permütasyon']},
{name:'Tarih',icon:'🏛',tone:'red',group:'gk',pct:78,topics:['İlk Türk Devletleri','Osmanlı Kuruluş','Osmanlı Kültür','Kurtuluş Savaşı','Atatürk İlkeleri','Cumhuriyet Dönemi']},
{name:'Coğrafya',icon:'🌐',tone:'blue',group:'gk',pct:70,topics:['Türkiye Fiziki Coğrafyası','İklim','Nüfus','Ekonomik Coğrafya','Bölgeler','Harita Bilgisi']},
{name:'Vatandaşlık',icon:'⚖',tone:'orange',group:'gk',pct:84,topics:['Hukukun Temelleri','Anayasa','Yasama','Yürütme','Yargı','İdare Hukuku']},
{name:'Güncel Bilgiler',icon:'▤',tone:'violet',group:'gk',pct:73,topics:['Türkiye Gündemi','Bilim ve Teknoloji','Kültür ve Sanat','Uluslararası Kuruluşlar','Ekonomi','Spor']}];
const bank=Array.isArray(window.KPSS_BANK)?window.KPSS_BANK.filter(q=>q&&Array.isArray(q.opts)&&q.opts.length>=2):[];
let state={correct:0,wrong:0,answered:0,wrongs:[],favorites:[],later:[],favoriteTopics:[],xp:0,planDone:[]};
try{Object.assign(state,JSON.parse(localStorage.getItem('kpssState')||'null')||{})}catch{}
state.wrongs=Array.isArray(state.wrongs)?state.wrongs:[];state.favorites=Array.isArray(state.favorites)?state.favorites:[];state.later=Array.isArray(state.later)?state.later:[];state.favoriteTopics=Array.isArray(state.favoriteTopics)?state.favoriteTopics:[];state.planDone=Array.isArray(state.planDone)?state.planDone:[];
const save=()=>{try{localStorage.setItem('kpssState',JSON.stringify(state))}catch{}};
let subject='Matematik',topic='',qi=0,choice=null,answered=false,qt=null,examSize=120,ei=0,ea=[],eq=[],examStart=0,et=null,examFinished=false,examReview=false,retryQueue=null;
const plans=[['Matematik','Problemler • 20 soru','Soru çözümü'],['Türkçe','Paragraf • 15 soru','Hızlı okuma'],['Tarih','Osmanlı • 10 soru','Konu tekrarı'],['Genel tekrar','Yanlışlar • 10 soru','Tekrar']];
const examPresets={10:['Hızlı Test',15],20:['Standart Deneme',30],30:['Yoğun Deneme',45],60:['Tam Performans',90],120:['Tam KPSS',130]};
const OSYM_KPSS='https://www.osym.gov.tr/SinavGrubu/Menu/344';
function toast(t){const x=$('toast');if(x){x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),1800)}}
function timers(){clearInterval(qt);clearInterval(et);qt=et=null}
function show(id){timers();document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.bottom button').forEach(x=>x.classList.toggle('on',x.dataset.go===id));({home,subjects:renderSubjects,topic:renderTopics,question:renderQuestion,exams:renderExams,examrun:renderExam,result:renderResult,wrongs:renderWrongs,stats:renderStats,profile:renderProfile,past:renderPast,plan:renderPlan}[id]||home)()}
function home(){const n=Math.min(50,state.answered||0),p=Math.round(n/50*100);if($('goalCount'))$('goalCount').innerHTML=n+' <span>/ 50 soru</span>';if($('goalPct'))$('goalPct').textContent='%'+p;if($('goalBar'))$('goalBar').style.width=p+'%';if($('ring'))$('ring').style.background='conic-gradient(#24dcb8 '+p+'%,#263b4e 0)';if($('todayWork'))$('todayWork').innerHTML=subjectData.slice(1,4).map(s=>'<div class="workrow"><span class="mini '+s.tone+'">'+s.name[0]+'</span><span><b>'+esc(s.name)+'</b> • '+esc(s.topics[0])+'</span><em>%'+s.pct+'</em></div>').join('');if($('planProgress'))$('planProgress').textContent=state.planDone.length+' / 4 tamamlandı';if($('planBar'))$('planBar').style.width=state.planDone.length*25+'%'}
function renderSubjects(){const q=($('subjectSearch')?.value||'').trim().toLocaleLowerCase('tr-TR'),tab=document.querySelector('#subjects .tabs button.active')?.dataset.tab||'gy',l=$('subjectList');if(!l)return;const list=subjectData.filter(s=>s.group===tab&&(!q||s.name.toLocaleLowerCase('tr-TR').includes(q)||s.topics.some(t=>t.toLocaleLowerCase('tr-TR').includes(q))));l.innerHTML=list.length?list.map(s=>'<button class="subject" data-sub="'+encodeURIComponent(s.name)+'"><span class="subicon '+s.tone+'">'+s.icon+'</span><span class="subinfo"><b>'+esc(s.name)+'</b><small>'+s.topics.length+' konu • '+bank.filter(x=>x.subject===s.name).length+' soru</small></span><span class="score">%'+s.pct+'</span><span>›</span></button>').join(''):'<section class="card"><b>Sonuç bulunamadı.</b><p class="muted">Ders veya konu adını değiştirerek tekrar ara.</p></section>'}
function renderTopics(){const s=subjectData.find(x=>x.name===subject)||subjectData[1],l=$('topicList');if(!l)return;const fav=state.favoriteTopics.includes(s.name);if($('topicTitle'))$('topicTitle').textContent=s.name;if($('topicName'))$('topicName').textContent=s.name;if($('topicMeta'))$('topicMeta').textContent=s.topics.length+' konu • '+bank.filter(q=>q.subject===s.name).length+' soru';const favBtn=document.querySelector('#topic .topbar [data-action="favoriteTopic"]');if(favBtn)favBtn.textContent=fav?'★':'☆';l.innerHTML=s.topics.map(t=>{const n=bank.filter(q=>q.subject===s.name&&q.topic===t).length;return '<button class="topic" data-topic="'+encodeURIComponent(t)+'"><span class="grow"><b>'+esc(t)+'</b><small>'+n+' soru • Konuyu çözmek için aç</small></span><span class="topicScore low">%'+Math.max(55,s.pct-s.topics.indexOf(t)*2)+'</span><span>›</span></button>'}).join('')}
function qlist(){if(retryQueue?.length)return retryQueue;const a=bank.filter(q=>q.subject===subject&&(!topic||q.topic===topic));if(a.length)return a;const b=bank.filter(q=>q.subject===subject);return b.length?b:bank}
function renderQuestion(){const a=qlist();if(!a.length){toast('Soru bankası yüklenemedi');return}const q=a[qi%a.length];$('qcategory').textContent=q.subject+' • '+q.topic;$('qsubject').textContent=q.subject;$('qnum').textContent=qi+1;$('qtotal').textContent=a.length;$('qtext').textContent=q.text;$('qbar').style.width=((qi%10+1)*10)+'%';$('options').innerHTML=q.opts.map((o,i)=>'<button class="option '+(choice===i?'selected ':'')+(answered&&i===q.a?'correct ':'')+(answered&&choice===i&&i!==q.a?'wrong':'')+'" data-option="'+i+'"><span class="letter">'+String.fromCharCode(65+i)+'</span>'+esc(o)+'<span class="mark">'+(answered&&i===q.a?'✓':answered&&choice===i?'×':'')+'</span></button>').join('');$('explain').style.display=answered?'block':'none';$('explain').innerHTML=answered?'<b>Çözüm</b><p>'+esc(q.e||'Bu soru için açıklama bulunmuyor.')+'</p>':'';$('answerBtn').textContent=answered?'Sonraki Soru →':'Cevabı İşaretle';if(answered){clearInterval(qt)}else{clearInterval(qt);let left=102;const tick=()=>{if($('timer'))$('timer').textContent=String(Math.floor(left/60)).padStart(2,'0')+':'+String(left%60).padStart(2,'0');if(left<=0){clearInterval(qt);toast('Süre doldu')}else left--};tick();qt=setInterval(tick,1000)}}
function renderExams(){const l=$('examList');if(!l)return;l.innerHTML=Object.entries(examPresets).map(([size,v])=>'<button class="examrow '+(examSize===+size?'selected':'')+'" data-examsize="'+size+'"><span class="eico">▣</span><b>'+v[0]+'<small>'+size+' Soru</small></b><small>~ '+v[1]+' dakika</small><span>›</span></button>').join('');const b=document.querySelector('#exams [data-action="startExam"]');if(b)b.textContent=examSize+' Soruluk Denemeyi Başlat →'}
function startExam(){const src=bank.length?bank:[{subject:'KPSS',topic:'Genel',text:'İçerik yüklenemedi.',opts:['A','B','C','D','E'],a:0,e:''}];eq=Array.from({length:examSize},(_,i)=>src[i%src.length]);ei=0;ea=Array(examSize).fill(null);examStart=Date.now();examFinished=false;examReview=false;show('examrun')}
function renderExam(){const q=eq[ei];if(!q)return;$('examNumbers').innerHTML=eq.map((_,i)=>'<button type="button" class="'+(i===ei?'current ':'')+(ea[i]!==null?'done':'')+'" data-examjump="'+i+'">'+(i+1)+'</button>').join('');$('examQnum').textContent=ei+1;$('examQtext').textContent=q.text;$('examOptions').innerHTML=q.opts.map((o,i)=>'<button class="option '+(ea[ei]===i?'selected':'')+'" data-examoption="'+i+'"><span class="letter">'+String.fromCharCode(65+i)+'</span>'+esc(o)+'</button>').join('');const c=ea.filter((a,i)=>a!==null&&a===eq[i].a).length,w=ea.filter((a,i)=>a!==null&&a!==eq[i].a).length;$('examCorrect').textContent=c;$('examWrong').textContent=w;$('examBlank').textContent=examSize-c-w;const next=document.querySelector('#examrun [data-action="examNext"]');if(next)next.textContent=examReview?(ei<examSize-1?'Sonraki →':'İncelemeyi Bitir'):((ei<examSize-1)?'Sonraki →':'Sınavı Bitir');const prev=document.querySelector('#examrun [data-action="examPrev"]');if(prev)prev.disabled=ei===0;const min=examPresets[examSize]?.[1]||130;if(examReview){if($('examTimer'))$('examTimer').textContent='İNCELEME';return}clearInterval(et);const tick=()=>{const left=Math.max(0,min*60-Math.floor((Date.now()-examStart)/1000));$('examTimer').textContent=String(Math.floor(left/60)).padStart(2,'0')+':'+String(left%60).padStart(2,'0');if(left<=0)finishExam()};tick();et=setInterval(tick,1000)}
function finishExam(){if(examFinished)return;examFinished=true;clearInterval(et);const c=ea.filter((a,i)=>a!==null&&a===eq[i].a).length,w=ea.filter((a,i)=>a!==null&&a!==eq[i].a).length,b=examSize-c-w;state.correct+=c;state.wrong+=w;state.answered+=c+w;state.xp+=examSize;for(let i=0;i<examSize;i++)if(ea[i]!==null&&ea[i]!==eq[i].a)state.wrongs.unshift(eq[i]);state.wrongs=state.wrongs.slice(0,100);save();renderResultValues(c,w,b);show('result');toast('Deneme tamamlandı 🏆')}
function renderResultValues(c,w,b){if($('resultNet'))$('resultNet').textContent=(c-w/4).toFixed(2).replace('.',',');if($('rCorrect'))$('rCorrect').textContent=c;if($('rWrong'))$('rWrong').textContent=w;if($('rBlank'))$('rBlank').textContent=b;if($('rSuccess'))$('rSuccess').textContent='%'+Math.round(c/examSize*100);if($('rTime'))$('rTime').textContent=Math.max(1,Math.round((Date.now()-examStart)/60000))+' dk'}
function renderResult(){if($('resultNet')&&eq.length){const c=ea.filter((a,i)=>a!==null&&a===eq[i]?.a).length,w=ea.filter((a,i)=>a!==null&&a!==eq[i]?.a).length;renderResultValues(c,w,examSize-c-w)}}
function renderWrongs(){const l=$('wrongList');if(!l)return;l.innerHTML=state.wrongs.length?state.wrongs.map((w,i)=>'<section class="card"><small>Yanlış soru '+(i+1)+' • '+esc(w.subject||'KPSS')+'</small><h3>'+esc(w.text)+'</h3><p class="muted">'+esc(w.topic||'')+'</p><button class="primary" data-retry="'+i+'">Tekrar Çöz</button></section>').join(''):'<section class="card"><b>Harika! 🎉</b><p class="muted">Henüz yanlış kaydın yok.</p></section>'}
function renderStats(){const n=state.answered||0;$('totalQ').textContent=n;$('success').textContent='%'+(n?Math.round((state.correct||0)/n*100):0);$('net').textContent=((state.correct||0)-(state.wrong||0)/4).toFixed(1).replace('.',',')}
function renderProfile(){const x=state.xp||0;$('level').textContent=Math.max(1,Math.floor(x/400)+1);$('xpText').textContent=(x%2000).toLocaleString('tr-TR')+' / 2.000 XP';$('xpBar').style.width=Math.min(100,x%2000/20)+'%';$('calendar').innerHTML=Array.from({length:28},(_,i)=>'<div class="day '+(i%7===6?'active':'')+'">'+(i+1)+'<br><small>'+(i%3===0?'✓':'•')+'</small></div>').join('')}
let pastGroup='all';
function renderPast(){const l=$('pastList');if(!l)return;const years=Array.from({length:16},(_,i)=>2025-i);const rows=years.filter(y=>pastGroup==='all'||pastGroup==='lisans'||pastGroup==='onlisans'||pastGroup==='orta');l.innerHTML=rows.map(y=>'<section class="card"><div class="row"><span><b>KPSS '+y+'</b><small class="muted">Resmî ÖSYM soru kitapçığı ve cevap anahtarı</small></span><button class="link" data-pastyear="'+y+'">ÖSYM’yi aç ↗</button></div></section>').join('')}
function renderPlan(){const l=$('planList');if(!l)return;l.innerHTML=plans.map((p,i)=>'<section class="plan"><div class="row"><b>'+esc(p[0])+'</b><button class="link" data-plan="'+i+'">'+(state.planDone.includes(i)?'Tamamlandı ✓':'Tamamla')+'</button></div><p>'+esc(p[1])+' • '+esc(p[2])+'</p></section>').join('');$('weekPct').textContent='%'+state.planDone.length*25;$('weekBar').style.width=state.planDone.length*25+'%'}
function modal(t,b){if(!$('modal'))return;$('modalTitle').textContent=t;$('modalBody').innerHTML=b;$('modal').classList.add('open')}
function act(n){
if(n==='startExam')return startExam();
if(n==='examPrev'){if(ei>0){ei--;renderExam()}return}
if(n==='examNext'){if(examReview){if(ei<examSize-1){ei++;renderExam()}else{examReview=false;show('result')}return}if(ei<examSize-1){ei++;renderExam()}else finishExam();return}
if(n==='favorite'){const key=qi+'|'+subject+'|'+topic;state.favorites=state.favorites.includes(key)?state.favorites.filter(x=>x!==key):[...state.favorites,key];save();return toast(state.favorites.includes(key)?'Favorilere eklendi ⭐':'Favorilerden çıkarıldı')}
if(n==='later'){const key=qi+'|'+subject+'|'+topic;state.later=state.later.includes(key)?state.later.filter(x=>x!==key):[...state.later,key];save();return toast('Sonra çöz listesine kaydedildi ⏳')}
if(n==='explain'){const a=qlist(),q=a[qi%a.length];return modal('Çözüm','<p>'+esc(q.e||'Bu soru için açıklama bulunmuyor.')+'</p>')}
if(n==='clearWrongs'){state.wrongs=[];save();return renderWrongs()}
if(n==='closeModal')return $('modal').classList.remove('open');
if(n==='confirmExit'){if(!examFinished&&!examReview&&ea.some(x=>x!==null))return modal('Denemeden çık?','<p>İşaretlediğin cevaplar kaybolacak.</p><div class="row"><button data-action="closeModal">Devam Et</button><button class="primary" data-action="forceExit">Çık</button></div>');return show('exams')}
if(n==='forceExit'){return $('modal').classList.remove('open'),show('exams')}
if(n==='resetExam'){examSize=120;return renderExams()}
if(n==='focusSearch'){const x=$('subjectSearch');if(x){x.focus();x.scrollIntoView({behavior:'smooth',block:'center'})}return}
if(n==='settings')return modal('Ayarlar','<p>İlerleme, yanlışlar, favoriler ve çalışma planı bu cihazın tarayıcı depolamasında saklanır.</p>');
if(n==='allBadges')return modal('Rozetler','<p>🔥 7 Günlük Seri<br>🏆 500 Soru<br>🟢 %90 Başarı<br>💗 10 Konu<br>🔷 İlk Deneme<br>⚡ Hızlı Çözen</p>');
if(n==='pastInfo')return modal('ÖSYM arşivi','<p>Çıkmış sorular telifli olduğu için uygulama içinde kopyalanmaz. Yıllık kitapçık ve cevap anahtarları için resmî ÖSYM KPSS sayfasını kullan.</p><p><a href="'+OSYM_KPSS+'" target="_blank" rel="noopener">ÖSYM KPSS arşivini aç ↗</a></p>');
if(n==='resultAnalysis')return show('stats');
if(n==='reviewExam'){examReview=true;ei=0;show('examrun');return}
if(n==='share'){const text='KPSS 2026 deneme sonucu: '+($('resultNet')?.textContent||'0,00')+' net';if(navigator.share){navigator.share({title:'KPSS 2026 Sonucum',text}).catch(()=>{})}else if(navigator.clipboard){navigator.clipboard.writeText(text).then(()=>toast('Sonuç panoya kopyalandı 📋')).catch(()=>toast(text))}else toast(text);return}
if(n==='topicStats'){const s=subjectData.find(x=>x.name===subject),rows=s?s.topics.map(t=>t+': '+bank.filter(q=>q.subject===subject&&q.topic===t).length+' soru').join('<br>'):'Veri yok';return modal(subject+' • İstatistik',rows)}
if(n==='topicNotes'){const s=subjectData.find(x=>x.name===subject),t=topic||s?.topics[0]||'';return modal('Konu Notu','<p><b>'+esc(t)+'</b></p><p>Temel kavramları öğren, verilenleri sınıflandır, şıkları ele ve sonucu kontrol et. Yanlış yaptığın soruyu aynı gün tekrar çöz.</p>')}
if(n==='favoriteTopic'){const i=state.favoriteTopics.indexOf(subject);state.favoriteTopics=i<0?[...state.favoriteTopics,subject]:state.favoriteTopics.filter(x=>x!==subject);save();renderTopics();return toast(i<0?'Ders favorilere eklendi ⭐':'Favorilerden çıkarıldı')}
if(n==='editPlan')return modal('Plan düzenleme','<p>Her görevin yanındaki <b>Tamamla</b> düğmesiyle haftalık ilerlemeni güncelleyebilirsin.</p>');
if(n==='notify')return modal('Bildirimler','<p>Yeni bildirim yok. 🔔</p>');
if(n==='period')return toast('Son 30 gün görünümü seçildi');
if(n==='statsSubjects')return modal('Ders performansı',subjectData.map(s=>'<p><b>'+esc(s.name)+'</b> • %'+s.pct+'</p>').join(''));
if(n==='statsTopics')return modal('Konu performansı',subjectData.flatMap(s=>s.topics.slice(0,3).map(t=>'<p><b>'+esc(s.name)+'</b> • '+esc(t)+'</p>')).join(''));
}
function click(e){
const go=e.target.closest('[data-go]');if(go){e.preventDefault();retryQueue=null;show(go.dataset.go);return}
const sub=e.target.closest('[data-sub]');if(sub){const name=decodeURIComponent(sub.dataset.sub||'');const s=subjectData.find(x=>x.name===name);if(s){subject=s.name;topic='';retryQueue=null;show('topic')}return}
const tp=e.target.closest('[data-topic]');if(tp){topic=decodeURIComponent(tp.dataset.topic||'');qi=0;choice=null;answered=false;retryQueue=null;show('question');return}
const sz=e.target.closest('[data-examsize]');if(sz){examSize=+sz.dataset.examsize||120;renderExams();return}
const op=e.target.closest('[data-option]');if(op&&!answered){choice=+op.dataset.option;renderQuestion();return}
const eo=e.target.closest('[data-examoption]');if(eo&&!examReview){ea[ei]=+eo.dataset.examoption;renderExam();return}
const ej=e.target.closest('[data-examjump]');if(ej){ei=Math.max(0,Math.min(examSize-1,+ej.dataset.examjump));renderExam();return}
const p=e.target.closest('[data-plan]');if(p){const i=+p.dataset.plan;state.planDone=state.planDone.includes(i)?state.planDone.filter(x=>x!==i):[...state.planDone,i];save();renderPlan();home();return}
const retry=e.target.closest('[data-retry]');if(retry){const i=+retry.dataset.retry,q=state.wrongs[i];if(q){retryQueue=[q];subject=q.subject;topic=q.topic||'';qi=0;choice=null;answered=false;show('question')}return}
const py=e.target.closest('[data-pastyear]');if(py){window.open(OSYM_KPSS,'_blank','noopener');toast(py.dataset.pastyear+' için ÖSYM KPSS arşivi açıldı ↗');return}
const answer=e.target.closest('#answerBtn');if(answer){const a=qlist(),q=a[qi%a.length];if(answered){qi++;choice=null;answered=false}else{if(choice===null)return toast('Önce bir seçenek işaretle');answered=true;state.answered++;state.xp++;if(choice===q.a)state.correct++;else{state.wrong++;state.wrongs.unshift(q);state.wrongs=state.wrongs.slice(0,100)}save()}renderQuestion();return}
const b=e.target.closest('[data-action]');if(b){e.preventDefault();act(b.dataset.action);return}
const pt=e.target.closest('[data-pastgroup]');if(pt){document.querySelectorAll('#past .pastTabs button').forEach(x=>x.classList.remove('active'));pt.classList.add('active');pastGroup=pt.dataset.pastgroup||'all';renderPast();return}
if(e.target.closest('#exams .tabs button')){const t=e.target.closest('#exams .tabs button');document.querySelectorAll('#exams .tabs button').forEach(x=>x.classList.remove('active'));t.classList.add('active');toast(t.textContent.trim()+' seçildi');return}
if(e.target.closest('#subjects .tabs button')){const t=e.target.closest('#subjects .tabs button');document.querySelectorAll('#subjects .tabs button').forEach(x=>x.classList.remove('active'));t.classList.add('active');renderSubjects();return}
}
document.addEventListener('click',click,{passive:false});
document.addEventListener('input',e=>{if(e.target.id==='subjectSearch')renderSubjects()});
window.addEventListener('pageshow',()=>show(document.querySelector('.screen.active')?.id||'home'));
window.addEventListener('beforeunload',save);
home();window.__KPSS_RUNTIME__={show,bank,state};
})();
